### ISSUE TITLE
TypeError: Cannot read property 'allStrapiArticle' of undefined

### ISSUE THREAD

**Issue by BoraKilicoglu** [strapi/gatsby-source-strapi#1]
Hello, 

I'm following your "Building a static blog using Gatsby and Strapi" article, then i'm getting this issue! "TypeError: Cannot read property 'allStrapiArticle' of undefined" 

What can be the reason? Thank you...

<img width="934" alt="screen shot 2018-01-26 at 16 48 48" src="https://user-images.githubusercontent.com/1382214/35442612-f10728e4-02b8-11e8-8179-392ec6255d15.png">

**Comment by RoymanJing** [comment]
did the issue go? how do you fix it? what's the reason, I got the same error.

**Comment by adamtysonsmith** [comment]
@BoraKilicoglu How did you resolve this issue?

**Comment by PovarovDenis** [comment]
Any updates?

**Comment by guilhermecomum** [comment]
Two things:

1. Make sure your model name is on singular
2. On Users & Permissions make sure User Permission `find` is checked
