### ISSUE TITLE
Gatsby not fetching data from cms.

### ISSUE THREAD

**Issue by wilitp** [strapi/gatsby-source-strapi#101]
System: Ubuntu 18.04.4 LTS

I've just started a gatsby project with the "hello world" starter and installed the gatsby-source-strapi plugin. But when running both, the cms(locally) and gatsby dev server, the bundle finishes and the "Fetched Strapi Data" is still shown as loading. When using graphiql, I'm NOT being able to query content from strapi; in fact, the queries are not even documented.

**Comment by wilitp** [comment]
Sometimes the plugin will throw a ETIMEDOUT error too. I'm setting the plugin just like in the docs and the endpoints work when hitting them with chrome.

**Comment by wilitp** [comment]
I now tried using "npx gatsby new" instead of using the installed gatsby-cli (which is up to date) and worked just fine. Still don't know what the problem was.

**Comment by bruno-vaz** [comment]
I'm having the same problem, but running `npx gatsby new` did not work.

**Comment by leventemathe** [comment]
Same issue, stuck on "Fetched Strapi Data" and "source and transform nodes" on localhost.
It used to be fine for months, then it just stopped working today. 
Everything builds fine on netlify.

**Comment by wokalamps** [comment]
I had the api endpoints set in "contentTypes" which does not work. I had this to change to the collectiontype name in singular. 
eg.: If you have a collection Type "Products" the config should look this:
```... configTypes: [`Product`], ...```
