### ISSUE TITLE
Error: There was an error in your GraphQL query:  Cannot query field "allStrapiPage" on type "Query". Did you mean "allSitePage"?

### ISSUE THREAD

**Issue by bnjmnjns** [strapi/gatsby-source-strapi#103]
Hi!
I'm trying to use this plugin, but having a bit of trouble. To begin with this was happening 1/2 the time I was starting gatsby, now it's 100% of the time.

```
There was an error in your GraphQL query:

Cannot query field "allStrapiPage" on type "Query". Did you mean "allSitePage"?

GraphQL request:3:5
2 |   query IndexQuery {
3 |     allStrapiPage {
  |     ^
4 |       edges {

File: /Users/BenjaminJones/Documents/Code/loose-antenna/loose-antenna-web/src/pages/index.js
```

Here's my `gatsby-config.js`

```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
    description:
      'Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.',
    author: '@gatsbyjs',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: 'http://localhost:1338',
        contentTypes: ['page', 'user', 'show', 'host', 'upcomingShow'],
        queryLimit: 1000,
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'images',
        path: `${__dirname}/src/images`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-styled-components',
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
};
```

here's my page component:

```
import React from 'react';
import { graphql } from 'gatsby';

import Layout from '../components/layout';

import SEO from '../components/seo';


const IndexPage = ({ data }) => {
  const pageData = data?.allStrapiPage?.edges[0].node;

  return (
    <>
      <SEO title={pageData?.title} description={pageData?.description} />
      <Layout>{/* <Schedule schedule={pageData} /> */}</Layout>
    </>
  );
};

export const pageQuery = graphql`
  query IndexQuery {
    allStrapiPage {
      edges {
        node {
          title
          description
        }
      }
    }
  }
`;

export default IndexPage;
```

and I've verified I have my strapi backend running and that there are entries in the Pages content type. Any ideas?

using:
gatsby-source-strapi: "^0.0.10"
gatsby: "^2.18.12",
strapi: "3.0.0-beta.18.4"

Thanks!

Edit I've also checked in http://localhost:1338/graphql using the following query and get the response I was expecting: 
```
{
  "data": {
    "pages": [
      {
        "title": "index",
        "description": "this is the first page"
      },
      {
        "title": "page_2",
        "description": "this is the other page"
      }
    ]
  }
}
```

**Comment by wilitp** [comment]
Try using the graphiql page in the dev server (localhost:8000/__graphql). There, you should be able to test you queries. If the query is not there, you should try adding some content for that content type.

**Comment by wilitp** [comment]
If neither of those solve your problem, try using npx to start the project. I'm not sure of the reason but this worked for me.

**Comment by kyuumeitai** [comment]
@bnjmnjns Hi there
The gatsby path is sourced by the REST version of your strapi, not the graphql side.

Check this URL:

http://localhost:1338/pages

I'll bet that you're missing permissions for your `page` collection in strapi, for this you have to check the "Roles & Permissions" in your strapi admin page, then go to "public" and check the "count", "find" and "findone" permissions, then save in the top right button and try again.

Once you see the http://localhost:1338/pages json you could try in Gatsby

Good luck!

**Comment by Chiqui1234** [comment]
Same error here. I can fetch data from GraphQL Playground on Strapi, but when I run the same query on Gatsby page or GraphiQL (GraphiQL runs in port 8000, same as Gatsby).
I have permissions for public user and the json looks fine when visiting (for example) localhost:1337/brands :D 

I have Strapi on 1337 port: My gatsby-config.js is
```javascript
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})

module.exports = {
  siteMetadata: {
    title: "Tutorial de Holanerd",
    description: "Un sitio web que almacena empresas",
    author: "Santiago Gimenez",
  },
  plugins: [
    "gatsby-plugin-react-helmet",
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: "gatsby-source-strapi",
      options: {
        apiURL: process.env.API_URL || "http://localhost:1337",
        contentTypes: [
          // List of the Content Types you want to be able to request from Gatsby.
          "brand",
          "category",
        ],
        queryLimit: 1000,
      },
    },
    "gatsby-transformer-sharp",
    "gatsby-plugin-sharp",
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: "gatsby-starter-default",
        short_name: "starter",
        start_url: "/",
        background_color: "#663399",
        theme_color: "#663399",
        display: "minimal-ui",
      },
    },
    "gatsby-plugin-offline",
  ],
}
```

Where's the problem? :O

**Comment by ericliu121187** [comment]
I am running into a similar (if not the same) issue. 

**Strapi locally**
- Able to hit `http://localhost:1337/posts?_limit=100` from Insomnia

**Gatsby**
- Unable to hit the local endpoint, getting the `Cannot query field "allStrapiPage" on type "Query".` error. Also doesn't show up in localhost:8000/__graphql
- When switching to hit the staging server (not local), it works as expected

**Comment by AllStackDev1** [comment]
> I am running into a similar (if not the same) issue.
> 
> **Strapi locally**
> 
> * Able to hit `http://localhost:1337/posts?_limit=100` from Insomnia
> 
> **Gatsby**
> 
> * Unable to hit the local endpoint, getting the `Cannot query field "allStrapiPage" on type "Query".` error. Also doesn't show up in localhost:8000/__graphql
> * When switching to hit the staging server (not local), it works as expected

Have you been able to solve this issue?

**Comment by luansemensato** [comment]
Have you managed to solve this problem?

**Comment by ericliu121187** [comment]
Hi, I don't remember. I think it ended up being a permissions issue, may need to enable specific permissions on the entities from your Strapi admin.

**Comment by remidej** [comment]
Hey folks, I'm closing this issue as it was most likely a config/permissions issue, not an actual bug from the plugin.

And note that now that we released the v1, you should rename contentTypes to collectionTypes in your config 🙂
