### ISSUE TITLE
Paginate Strapi data requests

### ISSUE THREAD

**Issue by gautham20** [strapi/gatsby-source-strapi#104]
I have around 1500 articles in Strapi. When I set the `queryLimit: 1500`, the request that goes out is,

`https://<straiphost>/articles?_limit=1500`

this call fails due to data size limitations in the underlying sqlite db.
Since these requests are made only during the build process, I'm not looking forward to switching to some other database such as Mongo.

Is it possible to paginate the requests? for instance, splitting it into 3 requests?

`https://<straiphost>/articles?_limit=500`
`https://<straiphost>/articles?_limit=500&_start=500`
`https://<straiphost>/articles?_limit=500&_start=1000`

A feature that exposes pagination params, along with `querylimit` will be a perfect fit for this. I think this will be a useful feature in the plugin to deal with large data size. Are there issues with taking this pagination approach?

**Comment by laurenskling** [comment]
Totally agree. I'm planning a Strapi Gatsby project with 200.000 items in a collection. To get all this data loaded to Gatsby I would have to make a single request limited to `_limit=200000`? 😱

**Comment by philippeauriach** [comment]
Made a PR for that : https://github.com/strapi/gatsby-source-strapi/pull/199

**Comment by alexmcgil** [comment]
Hi, i found solution on [Strapi doc](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/sort-pagination.html#pagination-by-page).

Change in path: ./config/api.js

`
module.exports = ({ env }) => ({
  responses: {
    privateAttributes: ['_v', 'id', 'created_at'],
  },
  rest: {
    defaultLimit: 100,    // this
    maxLimit: 250,        // or this
  },
});
 `
