### ISSUE TITLE
Sourcing will not work with Strapi Single Type in v3.0.0-beta.19.1

### ISSUE THREAD

**Issue by meinvolk** [strapi/gatsby-source-strapi#109]
When adding a **Single Type** content type to the Gatsby-Config contentType string array, the plugin will throw the error '**"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle**' when trying to build the front-end for Gatsby.

**Comment by meinvolk** [comment]
I wouldn't mind trying to figure this one out, but am unsure about how I would go about debugging the plugin itself.

**Comment by meinvolk** [comment]
A current workaround for this issue is to use the **gatsby-source-graphql** plugin.

**Comment by tomolenet** [comment]
This plugin can only handle array responses of strapi. But Single Type requests result in an object response. A very quick and dirty workaround is to check if the response of a request is an array or an object. If it is an object convert it to an array. You can do this by editing the `src/fetch.js` of the `gatsby-source-strapi` plugin .

```
  // Make API request.
  const documents = await axios(apiEndpoint, fetchRequestConfig)

  // Make sure response is an array.
  const response = documents.data.length ? documents.data : [ documents.data ]

  // Map and clean data.
  return response.map(item => clean(item))

```

**Comment by meinvolk** [comment]
Cool! Yea I found this out last night and started to work on a solution in hopes I could contribute. Will keep this thread posted. Thanks @tomolenet

**Comment by meinvolk** [comment]
I have opened a PR for this [issue](https://github.com/strapi/gatsby-source-strapi/pull/110).

**Comment by w3b-dev** [comment]
@meinvolk You have no idea how grateful I am. 😄
I am new to Strapy/Gatsby and for most of the day I was trying to debug why the hell I cannot use a single type. And you solved my problem pretty much the same day. 😄 

I realized after some debugging that first it looks for an object and second no option exists for single types. (I just assumed it would). Then I found your solution. It looks pretty good to me. Is it going to reach master any time soon so I don’t have to load a custom module?

**Comment by meinvolk** [comment]
I messaged @soupette on slack the other day asking when he was going to release v11 onto npm. But I know he is **super busy** with the Strapi project currently. I do believe they (Strapi Team) is looking for someone to manage this plugin. Although the newest release probably won't include this code, since it has not been reviewed or merged. My advice would be to just fork it for now and host it as your own NPM package.

**Comment by meinvolk** [comment]
The [PR](https://github.com/strapi/gatsby-source-strapi/pull/110) for this enhancement has been merged. Closing the ticket.

**Comment by pitkes22** [comment]
Any estimation when this will be released to NPM ?
