### ISSUE TITLE
Content Types with irregular Collection Names

### ISSUE THREAD

**Issue by maxkrass** [strapi/gatsby-source-strapi#113]
**Describe the bug**
The plugin cannot fetch content types if they have an irregular collection name

**Steps to reproduce the behavior**

1. Create content type with an irregular collection name (e.g. content type `Person`, collection name `People`)
2. Request the content type by gatsby-source-strapi

**Expected behavior**
You should be able to specify, whether the content type has an irregular collection name, and if yes, what it is.
The plugin should then be able to fetch those content types.

**Code snippets**

   ```
    "gatsby": "^2.19.45",
    "gatsby-source-filesystem": "^2.1.56",
    "gatsby-source-strapi": "^0.0.11",
```
_package.json_

**System**

- Node.js version: 10.16.3
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.19.3
- Database: SQLite
- Operating system: Windows 10 Pro x64

**Comment by SimonThormeyer** [comment]
I encountered the same problem, my Content Types have German names and in German plurals are almost regularly irregular.

the quick and maybe ugly fix that I am using is done as follows
in fetch.js:
`// Define API endpoint.
  let pluralizedContentType = contentType && contentType.plural
    ? contentType.plural
    : contentType
      ? pluralize(contentType)
      : undefined;
  let apiBase = singleType
    ? `${apiURL}/${singleType}`
    : `${apiURL}/${pluralizedContentType}``

in gatsby-node.js:
`const node = contentType.name
                  ?  Node(capitalize(contentType.name), item) 
                  :  Node(capitalize(contentType), item)`

in the projets root folder in gatsby-config.js ContentTypes can now be decalred like this:
`contentTypes: [
          // List of the Content Types you want to be able to request from Gatsby.
          {
            name: "person",
            plural: "people"
          },
        ],`
