### ISSUE TITLE
Using Single Types

### ISSUE THREAD

**Issue by stefba** [strapi/gatsby-source-strapi#116]
Hey.

I enabled my single type in `gatsby-config.js` via

`singleTypes: [
                  "site-information",
],`.

How do I query it?

It doesn’t show up anywhere in Gatsby’s GraphiQL interface.

Many thanks,

stef

**Comment by stefba** [comment]
Ok, I am realizing that the version Yarn downloads is not the current one of this repository. So I guess I just have to wait a bit?

stef

**Comment by meinvolk** [comment]
Yes, @alexandrebodin should release it shortly. Please close this ticket.

**Comment by alexandrebodin** [comment]
Hi, This was releas eunder 0.0.12

**Comment by stefba** [comment]
> Hi, This was released under 0.0.12

Now it works. Thank you very much!
