### ISSUE TITLE
Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by jacobherrington** [strapi/gatsby-source-strapi#12]
Following the [gatsby/strapi tutorial](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/) and I am running into an error message: `Cannot find module 'babel-runtime/regenerator'`

The message only shows up after I update gatsby-config.js with the gatsby-source-strapi plugin info.

Using Node 10.6.0 and npm 6.1.0.

**Comment by lauriejim** [comment]
I follow the tuto and I don't get any errors...

**Comment by jacobherrington** [comment]
Interesting, I'll give it another shot sometime. Thanks!

**Comment by appsolutegeek** [comment]
This is strange, as I also get the error, there is always some chatter over at gatsby saying its a known problem but I haven't seen any workaround or fix.

So I would be happy to know if somebody fixed it and how ?

A lot of the replies are saying to use node > 8 and not node 4. I am on Node 10

**Comment by jacobherrington** [comment]
@appsolutegeek That's interesting, maybe it's an issue with Node 10.

@lauriejim what version of Node where you using?

**Comment by appsolutegeek** [comment]
Hi,

There is some talk of the issue / similar issue here https://github.com/gatsbyjs/gatsby/issues/1905

One of the suggestion was to upgrade to gatsby beta, this does not work.

Although all other plugins don't seem to have this problem.

I hope we can get to the bottom of this as its stopping me from implementing strapi.

Would be interesting to know what versions of node - others are using that don't have the problem, if it's truly related to the node version.

**Comment by appsolutegeek** [comment]
Hi, I just went back to 8.11.2

➜  my-new-blog node --version
v8.11.2

and same issue.

```
 Error: Cannot find module 'babel-runtime/regenerator'

  - v8-compile-cache.js:159 require
    [my-new-blog]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-node.js:3 Object.<anonymous>
    [Personal]/[gatsby-source-strapi]/gatsby-node.js:3:20

  - v8-compile-cache.js:178 Module._compile
    [my-new-blog]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - module.js:11 require
    internal/module.js:11:18

  - api-runner-node.js:87 runAPI
    [my-new-blog]/[gatsby]/dist/utils/api-runner-node.js:87:20

  - api-runner-node.js:187
    [my-new-blog]/[gatsby]/dist/utils/api-runner-node.js:187:33

  - map.js:27
    [my-new-blog]/[async]/internal/map.js:27:9

  - eachOfLimit.js:64 replenish
    [my-new-blog]/[async]/internal/eachOfLimit.js:64:17

  - eachOfLimit.js:49 iterateeCallback
    [my-new-blog]/[async]/internal/eachOfLimit.js:49:17

  - onlyOnce.js:12
    [my-new-blog]/[async]/internal/onlyOnce.js:12:16

  - map.js:29
    [my-new-blog]/[async]/internal/map.js:29:13

  - util.js:16 tryCatcher
    [my-new-blog]/[bluebird]/js/release/util.js:16:23

  - nodeify.js:23 Promise.successAdapter
    [my-new-blog]/[bluebird]/js/release/nodeify.js:23:30

  - promise.js:566 Promise._settlePromise
    [my-new-blog]/[bluebird]/js/release/promise.js:566:21

```

**Comment by lauriejim** [comment]
I used node 9

**Comment by appsolutegeek** [comment]
Ok I am trying now with node 9 - I will report back.

**Comment by appsolutegeek** [comment]
Same problem for me,

```
➜  my-new-blog gatsby -version
1.9.277
➜  my-new-blog node --version
v9.11.2
```

and here is my gasby-config.js (removing the strapi plugin - allows me to do gatsby develop again).

```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://strapi.test-me.com`,
        contentTypes: [ // List of the Content Types you want to be able to request from Gatsby.
          `article`,
          `user`
        ]
      },
    },
  ],
}
```

**Comment by vepins** [comment]
I'm having the same problem with the [gatsby strapi tutorial](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/). 
`gatsby -version
1.1.581`
`node --version
v8.9.4`

Gatsby was running just fine. Changed gatsby-config.js based on instructions and couldn't restart the server. My config file is exactly the same as @appsolutegeek's (except for `apiURL`:  `localhost`).

**Comment by appsolutegeek** [comment]
So, I installed the latest plugin as I noticed there were some PR merged in. And now it appears to work. Well, I certainly didn't get the error.

Does anyone know what was fixed ? 

There was no update here, I just thought of updating to see if there was any improvement - and it seems I got lucky :-)

Would be nice to know what the problem was though.
