### ISSUE TITLE
Multiple node fields resolve to same GraphQL field

### ISSUE THREAD

**Issue by 0xhjohnson** [strapi/gatsby-source-strapi#126]
Wondering if you could point me in the right direction to fix these warnings about multiple node fields resolving to same GraphQL field. Things seem to be working fine but I try my best to handle warnings when they come in.

Error when running Gatsby develop:

```
warn Multiple node fields resolve to the same GraphQL field `StrapiArticle.author.avatar` - [`avatar`, `avatar___NODE`]. Gatsby will use `avatar___NODE`.
warn Multiple node fields resolve to the same GraphQL field `StrapiArticle.icon` - [`icon`, `icon___NODE`]. Gatsby will use `icon___NODE`.
```

Both of these refer to single media fields.

**Comment by HAHRJR94** [comment]
Buenas a todos, lo que hice fue hacer "gatsby clean" y luego "gatsby develop" y me funcionó. El proyecto lo hice con strapi.

**Comment by aravindjaimon** [comment]
I too have the same error Unable to use a same component twice on a single page. I fixed it by removing the components and adding the items as single items

**Comment by derrickmehaffy** [comment]
@HAHRJR94 please only use English here, but I have translated your message for others:

```
Hi everyone, what I did was do "gatsby clean" and then "gatsby develop" and it worked for me. I did the project with strapi.
```

**Comment by digitaldesigndj** [comment]
I trashed the `.cache` folder, but I guess `gatsby clean` is a better way. Cleared up my issues.

**Comment by hrahimi270** [comment]
Or you can just ignore it as I did ((:

**Comment by ggat** [comment]
For anyone still having this issue when using Single Media fields in strapi

```shell
yarn add gatsby-source-strapi@1.0.0-alpha.0
```

**Comment by Shams97** [comment]
guys I'm having the same warning and I run `gatsby clean` without difference.
NOTE : I'm not using strapi, instead these my library related to gatsby source : @robinmetral/gatsby-source-s3, gatsby-source-filesystem, gatsby-source-serverless-aurora
