### ISSUE TITLE
gatsby-and-strapi static blog error

### ISSUE THREAD

**Issue by Mr-Manna** [strapi/gatsby-source-strapi#13]
Having error while trying the  tutorial : https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/

$ gatsby develop
success delete html and css files from previous builds — 0.039 s
success open and validate gatsby-config — 0.017 s
success copy gatsby files — 0.746 s
success onPreBootstrap — 0.787 s
Starting to fetch data from Strapi (article)
Starting to fetch data from Strapi (user)
error Plugin gatsby-source-strapi returned an error

  Error: Request failed with status code 404

  - createError.js:16 createError
    [blog]/[axios]/lib/core/createError.js:16:15

  - settle.js:18 settle
    [blog]/[axios]/lib/core/settle.js:18:12

  - http.js:192 IncomingMessage.handleStreamEnd
    [blog]/[axios]/lib/adapters/http.js:192:11

  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9

**Comment by lauriejim** [comment]
I follow the tuto and I don't get any errors...

**Comment by Mr-Manna** [comment]
I thing there is some problem with my machine. I tried 'Cockpit Cms' also and Gatsby thrown same plug-in error! Trying to re-install everything today.

**Comment by lauriejim** [comment]
Okay @Mr-Manna good luck ;)

**Comment by Mr-Manna** [comment]
Well I think the problem is with Gatsby plugins, I've tried Gatsby-cockpit plugin and some other plugins all threw the same error. on other side I followed the Gatsby + Jekyll tutorial  and it worked smoothly without any issue.

**Comment by aleixhub** [comment]
maybe just faced the same issue, seems like each contentType inside the contentTypes list needs to be in plural (ex: articles) as well with the graphql query (ex: allStrapiArticles)

**Comment by wilitp** [comment]
I'm getting this same error while following the tuto step by step on. Has anyone come across the solution?
