### ISSUE TITLE
gatsby-source-strapi vs gatsby-source-graphql, which one to use and why?

### ISSUE THREAD

**Issue by Antoine-lb** [strapi/gatsby-source-strapi#134]
Hello,
This is more of a broad question than a error on it self.

Which one of this two plugins should be used and why? What are some diference that can be encountered developing in the long term with each plugin?

Side note: I'm currenlty running `gatsby-source-graphql` but I can't get to `childImageSharp`, does it has something to do with this where `gatsby-source-strapi` helps with the images, or both handle images well and this is a totally different issue?

Thanks!

**Comment by kachus22** [comment]
Would you mind sharing how are you doing it? How is your Collection type built?
It may be related to #98 
Provide more information in order to get better guidance

**Comment by Antoine-lb** [comment]
> Would you mind sharing how are you doing it? How is your Collection type built?
> It may be related to #98
> Provide more information in order to get better guidance

Using `gatsby-source-strapi` did solve the problems with the images, haven't really look further than that.

I personally wanted to use `gatsby-source-graphql` because the data has less layers and names are better.

**Comment by MrChrisRodriguez** [comment]
I'm using Strapi + Gatsby with the `gatsby-source-strapi` plugin and am still having issues with sharp extending **some** of my images in Graphql.
