### ISSUE TITLE
Will not load alternativeText from media

### ISSUE THREAD

**Issue by ergo-neil** [strapi/gatsby-source-strapi#137]
### Summary
I'm having a real weird issue when trying to get alternate text that is attached to media in my graphql query... If I set the media up as a single type
![single-media](https://user-images.githubusercontent.com/17163800/87061172-567dd900-c203-11ea-9468-ab6c74bc94bf.jpg)
I then don't get any alternativeText avaliable in the graphql query builder 
![graphql-no-alt(single media type)](https://user-images.githubusercontent.com/17163800/87061315-80cf9680-c203-11ea-9b6b-d29798b35836.jpg)

However if I set the media type to be multiple 
![multi-media](https://user-images.githubusercontent.com/17163800/87061443-a6f53680-c203-11ea-87c9-7da424ae15c2.jpg)
In my graphql builder the alternativeText field is there.
![graphql-with-alt(multi media type)](https://user-images.githubusercontent.com/17163800/87061741-0eab8180-c204-11ea-8a1c-47b3aa3a408a.jpg)

It seems to be impossible to get alternativeText when the media is a 'single media' type, is there any way around this or is it a bug?

### System:
OS: Ubuntu 16.04.6 LTS
Binaries:
Node: v10.18.1
npm: v6.13.4

npmGlobalPackages:
gatsby-cli: 2.22.15
gatsby-source-strapi: 0.0.12

**Comment by LilyLauben** [comment]
I'd like to bump this. It's also an issue I'm seeing on my project and it's very frustrating to either be unable to use the built-in alt and caption, or to be forced to use multiple image type fields all over my project, even where I only need one.

**Comment by ballPointPenguin** [comment]
I see this as well when I use media types within a single-type or a component type. It's like there's a whitelist of attributes or something. Querying my Strapi endpoint directly with GraphQL (not using gatsby) shows me all the attributes I expect to see. So my solution has been to stop using gatsby-source-strapi and use instead gatsby-source-graphql. https://www.gatsbyjs.com/plugins/gatsby-source-graphql/

**Comment by waynehaffenden** [comment]
+1 would like this too

**Comment by LilyLauben** [comment]
PR #118 looks like it does this, and also resolves a few other image related issues, so I hope it is merged in soon!
