### ISSUE TITLE
In-component media field cache problem in production

### ISSUE THREAD

**Issue by burlakko** [strapi/gatsby-source-strapi#144]
If media field e.g. image is inside of Strapi component, it's cache does not invalidate after file change.

In Strapi I have a content single type called `Outer`. Inside of it, I have a component called `Inner` with a media field called `Image`.
If I change the `Image` file in Strapi and rebuild the Gatsby content the image in static content remains the old one.

The bug is not reproducable in `develop` environment or in media field inside of `Outer` single type directly.

**Comment by rubilva** [comment]
Same problem here!
