### ISSUE TITLE
In production gatsby does not recognize the api from strapi

### ISSUE THREAD

**Issue by flevim** [strapi/gatsby-source-strapi#145]
I have successfully stored my backend with strapi in a heroku app but when integrating the url that heroku gives me to enter the strapi CMS, **gatsby** does not recognize it and does not load my queries and give me errors. 
When I had my strapi backend from localhost everything worked **fine**.

My configuration in _gatsby-config.js_ is: 
`
{
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL:'https://server-cambium.herokuapp.com/',
        contentTypes: [ // List of the Content Types you want to be able to request from Gatsby.
          'posts',
          'user'
        ],
        queryLimit: 1000,
      },
    },
`

And then give me classic error like :

- failed extract queries from components - 1.669s
- error  Cannot query field "allStrapiPosts" on type "Query"  graphql/template-strings
- error  Cannot query field "strapiPosts" on type "Query"  graphql/template-string

If anyone could tell me how to configure gatsby-config.js so that gatsby can recognize my backend in production it would be nice

**Comment by LilyLauben** [comment]
One thing that was causing errors for me was that I had to give the public user on Strapi 'find' and 'findAll' permissions before my gatsby API could connect successfully. [https://strapi.io/documentation/v3.x/plugins/users-permissions.html#manage-role-permissions](https://strapi.io/documentation/v3.x/plugins/users-permissions.html#manage-role-permissions)

**Comment by flevim** [comment]
I gave it the user and post permissions in strapi but it keeps giving me errors :(. I tried the problem [](https://github.com/strapi/strapi-examples/issues/128) and I couldn't get a satisfactory answer either ... I still don't understand why it gives me an error if I am giving it the url of the production api , maybe gatsby need some parameter to know that the url is in production... but i dont now.

**Comment by NikhilT27** [comment]
Hi, if you have given proper permission in strapi-heroku (Role and Permission - findone and find). And in gatsby-config-> gatsby-source-strapi -> used apiURL: "YOUR_STRAPI_NAME.herokuapp.com",(without any / or \). And its giving query result properly.

Then JUST change :-

**"queryLimit: 5000" (default is queryLimit: 1000) in gatsby-source-strapi.**

It worked for me. ;)

Try changing queryLimit value to some higher value.
