### ISSUE TITLE
Transformer remark integration

### ISSUE THREAD

**Issue by ThiagoMiranda** [strapi/gatsby-source-strapi#15]
Hi..
I was wondering if I can make content types with Strapi that will be consumed by the gatsby-transformer-remark and so on. The reason for that is that I use the gatbsy-remark-component to make custom components work in markdown files so I was wondering if I can "delegate" the content from Strapi to these plugins.

Thanks

**Comment by ThiagoMiranda** [comment]
I'm using this implementation:
https://github.com/strapi/gatsby-source-strapi/issues/5#issuecomment-399299309

Closing the issue :)

**Comment by dkarski** [comment]
@ThiagoMiranda how you transformed images inside in the WYSWIG content?

**Comment by lauriejim** [comment]
It's currently not possible.
It will come with [Media library](https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities) feature.
