### ISSUE TITLE
Cannot query field "allStrapiArticles" on type "Query".

### ISSUE THREAD

**Issue by lidachao111222** [strapi/gatsby-source-strapi#154]
Describe the bug:

I am getting this error when I use the Strapi v3.1.5. In the old version (v3.1.1), the code runing well... I don't know why. Could someone help me.

gatsby develop

I then get:

ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allStrapiArticles" on type "Query".

If you don't expect "allStrapiArticles" to exist on the type "Query" it is most likely a typo.
However, if you expect "allStrapiArticles" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allStrapiArticles" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src/components/HomePageComponents/LastRow.js:56:7

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

/Users/chaoli/Desktop/template/src/components/HomePageComponents/LastRow.js
  8:7  error  Cannot query field "allStrapiArticles" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

System

Node.js version: 12.14.1
NPM version: 6.14.5
Strapi version: 3.1.5
Database: sqlite3
Operating system: Catalina 10.15.6

**Comment by paul-ebose** [comment]
I think it's a typo on "allStrapiArticles". You can try using graphiql to check the queries available

**Comment by lidachao111222** [comment]
@paul-ebose Thanks man. Actually, I turned my Strapi to the old version.
