### ISSUE TITLE
Gatsby not fetching data from CMS.

### ISSUE THREAD

**Issue by felipefschwade** [strapi/gatsby-source-strapi#156]
I'm having a issue when data is added or updated from the CMS. When I do a update in Strapi CMS or add new data, I need to restart my gatsby frontend so it runs and read my updates in Strapi. Otherwise my new data is shown normal in Strapi but not in Gatsby, even in Gatsby Graphql. Is it a normal behaviour?

**Comment by vikingsvball** [comment]
Yes, if it's through the Dev environment, that's perfectly normal. Once you have it in production, there's a webhook you can add that will update your gatsby site automatically.

**Comment by wereallmonks** [comment]
Yess If it's through the Dev environment, that's perfectly normal. Once you have it in production, there's a webhook you can add that will update your gatsby site automatically.

**Comment by felipefschwade** [comment]
That's it then, there is any example of how this webhooks works?

**Comment by paul-ebose** [comment]
Here are some links to help out 

https://www.gatsbyjs.com/cloud/docs/strapi/getting-started/

https://github.com/strapi/strapi/blob/daaf1392d217a5927ea40320881bfec3208c9927/docs/3.0.0-beta.x/guides/webhooks.md

https://m.youtube.com/watch?v=u5NQd8ruPl4
