### ISSUE TITLE
GraphQL Error Unknown field `allStrapiArticle` on type `RootQueryType`

### ISSUE THREAD

**Issue by omerkunul** [strapi/gatsby-source-strapi#16]
**Node.js versionv10.8.0:

**npm version6.2.0:

**Strapi version3.0.0-alpha.13.0.1:

**Operating systemMacOs 10.14 Beta (18A353d):

Success delete html and css files from previous builds — 0.019 s
success open and validate gatsby-config — 0.006 s
success copy gatsby files — 0.018 s
success onPreBootstrap — 0.094 s
⠁ Starting to fetch data from Strapi (article)
Starting to fetch data from Strapi (user)
Fetch Strapi data: 38.918ms
The new node didn't pass validation
ValidationError: child "id" fails because ["id" must be a string]**

(node:3635) Warning: No such label 'Fetch Strapi data' for console.timeEnd()
warning The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes — 0.071 s
success building schema — 0.106 s
success createLayouts — 0.031 s
success createPages — 0.001 s
success createPagesStatefully — 0.019 s
success onPreExtractQueries — 0.001 s
success update schema — 0.068 s
**GraphQL Error Unknown field allStrapiArticle on type RootQueryType**

file: /Users/omerkunul/gatsby-strapi-tutorial/blog/src/pages/index.js
```javascript
1 |
2 | query IndexQuery {

3 | allStrapiArticle {
| ^
4 | edges {
5 | node {
6 | id
7 | title
8 | content
9 | }
10 | }
11 | }
12 | }
13 |
```

**Comment by rezof** [comment]
did you add article to contentTypes on gatsby-config.js ?

**Comment by omerkunul** [comment]
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337`,
        contentTypes: [ // List of the Content Types you want to be able to request from Gatsby.
          `article`,
          `user`
        ]
      },
    },
  ],
}

**Comment by rezof** [comment]
seems like you have some bad entry ... double check the data on the db

> The new node didn't pass validation
> ValidationError: child "id" fails because ["id" must be a string]**
...
> warning The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?

**Comment by GlynL** [comment]
I encountered this error and solved it by restarting the gatsby server (closing and running `gatsby develop`).

**Comment by georgezouq** [comment]
I have the same error, did you fix this??

**Comment by navinweb** [comment]
in gatsby-config.js instead of 'article' write 'articles'.
@georgezouq

**Comment by mkempinsky** [comment]
When I saw this error I was naming it wrong. I was trying to do:
`allContentfulStaffPost
`
When it should have been:
`allContentfulStaff`

It looks for the "name" key in the json object.

![screen shot 2018-12-06 at 12 41 28 pm](https://user-images.githubusercontent.com/20213691/49610756-54cb9f80-f954-11e8-82cd-308f004c8f1f.png)

**Comment by demo-Ghost** [comment]
Hey there!

I had the same issue with you guys. I was checking out the strapi tutorial for creating a blog with gatsby.js.

The problem for me was that, although I had changed the API access permissions for "articles" and checked the "find" option, I hadn't done the same for User in the "User-Permissions" section.

![image](https://user-images.githubusercontent.com/37753045/50702265-101d4c00-1059-11e9-9771-618e5c8fa26f.png)

This issue also seems to have been addressed by @pierreburgy in the comment section of this blog article:

https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/

and also here:

https://github.com/strapi/strapi-examples/issues/9

**Comment by rolandsaven** [comment]
I had all permission set up properly and still didn't work until I deleted `.cache` folder.
