### ISSUE TITLE
Images in dynamic zone

### ISSUE THREAD

**Issue by Sqveeze** [strapi/gatsby-source-strapi#161]
Hello,

Our team using gatsby source strapi for a project.

We have the following collections in strapi:

article
articleEnglish

both content type has a dynamic zone that has three fields:

text,
image,
images,

The problem is the following:

When gatsby-node runs the query the content field of the content type only "knows" about the text component field in the dynamic zone, and the other ones like images and image is not visible and the query will throw error. field "images" doesn't exist on type ...

I have tried to create the schema manually, but that always returns "null".

Any idea?

**Comment by gmourier** [comment]
Hi Sqveeze. Have you checked if data is given on REST endpoint ?
