### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by dsfrederic** [strapi/gatsby-source-strapi#162]
Hi, 

I'm not able to retrieve items from strapi with an authenticated user. 

Am I doing something wrong? 

Things I tried: 
- I was able successfully retrieved the data with API requests as described in this [doc](https://strapi.io/documentation/v3.x/guides/auth-request.html#login-as-a-reader)
- without login section in gatsby config it is able to retrieve the data since it is publicly accessible
- adding ALL permissions to an authenticated user role

gatsby-config.js
```js
{
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: process.env.API_URL,
        queryLimit: 1000, // Default to 100
        contentTypes: [`product`],
        //If using single types place them in this array.
        singleTypes: [],
        // Possibility to login with a strapi user, when content types are not publically available (optional).
        loginData: {
          identifier: process.env.API_EMAIL,
          password: process.env.API_PASSWORD,
        },
      },
    },
```

env.development
```
API_URL=http://localhost:1337
API_USERNAME=frontend-application
API_PASSWORD="REDACTED"
API_EMAIL="REDACTED"
```

Authenticated role permissions
![image](https://user-images.githubusercontent.com/28486949/99147339-7c6b2c80-2680-11eb-86d4-33d45f3923c9.png)

package.json
```
...
"dependencies": {
    "@babel/runtime": "^7.12.5",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/react-fontawesome": "^0.1.12",
    "@stripe/stripe-js": "^1.11.0",
    "babel-plugin-styled-components": "^1.11.1",
    "bootstrap": "^4.5.3",
    "gatsby": "^2.25.3",
    "gatsby-image": "^2.4.21",
    "gatsby-plugin-fontawesome-css": "^1.0.0",
    "gatsby-plugin-manifest": "^2.5.2",
    "gatsby-plugin-offline": "^3.3.3",
    "gatsby-plugin-react-helmet": "^3.3.14",
    "gatsby-plugin-sharp": "^2.8.0",
    "gatsby-plugin-styled-components": "^3.4.0",
    "gatsby-source-filesystem": "^2.4.2",
    "gatsby-source-strapi": "0.0.12",
    "gatsby-transformer-sharp": "^2.6.0",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "react": "^16.14.0",
    "react-datepicker": "^3.3.0",
    "react-dom": "^16.14.0",
    "react-helmet": "^6.1.0",
    "react-with-direction": "^1.3.1",
    "reactstrap": "^8.7.1",
    "styled-components": "^5.2.1",
    "use-shopping-cart": "^2.1.0"
  },
...
```

**Comment by denforlatte** [comment]
Have you tried adding `require('dotenv').config()` to the top of gatsby-config.js? 

You don't need to install dotenv as a dependency because it should be installed by Gatsby but I think the gatsby setup files run before the env vars are brought in, so you need to do it yourself.

**Comment by remidej** [comment]
> Have you tried adding `require('dotenv').config()` to the top of gatsby-config.js?

That should fix it [according to Gatsby's docs](https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/)
