### ISSUE TITLE
Images do not have publicURL option

### ISSUE THREAD

**Issue by burlakko** [strapi/gatsby-source-strapi#166]
UPD. Appears to be a documentation problem. Pls check the last comments

It seems plugin does not save media files from Strapi, so `publicURL` option is unavailable

### Steps to reproduce.

1. I  created blank Strapi project and Gatsby instance from https://github.com/gatsbyjs/gatsby-starter-hello-world starter.

2. In Strapi Content-types builder I created one single type and one collection type and added reading rights for public user.

3. I installed gatsby-source-strapi. Version from `yarn.lock`: `version "1.0.0-alpha.0"`.

4. Contents of `gatsby-config`:
```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337`,
        contentTypes: [`collection-type`],
        singleTypes: [`single-type`],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
  ],
}
```

5. Contents of `pages/index.js`:
```
import React from "react"
import { graphql } from "gatsby"

export default function Home({ data: { strapiSingleType, strapiCollectionType } }) {
  console.log("single ", strapiSingleType)
  console.log("collection ", strapiCollectionType)

  return <div>Hello world!</div>
}

export const query = graphql`
  query mainPageQuery {
    strapiSingleType {
      title
      image {
        localFile {
          publicURL
        }
      }
    }
    strapiCollectionType {
      title
      image {
        localFile {
          publicURL
        }
      }
    }
  }
`
```

6. Got `Cannot query field "publicURL" on type "File".` error.

7. Graphql helpre screenshot shows no `publicURL` option nor in `image` neither in `image.localFile`
![Screenshot_2020-11-30 GraphiQL(1)](https://user-images.githubusercontent.com/4548361/100591705-cd288980-32fe-11eb-95ca-9efc2458389c.png)

### Specifications
* OS Ubuntu Ubuntu 20.04
* Node 12.19.0
* Npm 6.14.8
* Strapi 3.3.4
* Gatsby 2.26.1
* Mongo

**Comment by burlakko** [comment]
Okay the plugin does copy images, there is an `url` option instead of `publicURL` with proper image url  and the query with `childImageSharp` returns undefined.
So the problem is the README still specify `publicURL` option

**Comment by burlakko** [comment]
Also can you please update README with example of custom schema with media files? I used `image: File @link(from: "localFile___NODE")` notation with previous version, but now it doesn't work.

**Comment by anedisi** [comment]
What is the current state of this. Some field get the publicURL prop and some don't. If i cycle the cache and other thing enough times it somehow works then.

**Comment by jonokercher1** [comment]
Looks like a version issue? Installing [gatsby-source-strapi@alpha](https://github.com/strapi/gatsby-source-strapi#install) fixed this for me

**Comment by berkaltug** [comment]
This is not solved i guess, i am facing same issue with the op . Sometimes in the graphql i see image fields has url , sometimes they have publicURL . And of course the orher fields change too.
I realized when it returns "url" field , the all fields are same as the fields that returns from strapi. Non-modified . Graphql wont run on them i guess.
When it returns publicURL , i see that they are the modified fields by graphql plugin. 
Os: Ubuntu 18
Here is my dependencies:
` {
    "bootstrap": "^5.0.0",
    "gatsby": "^3.1.1",
    "gatsby-plugin-gatsby-cloud": "^2.1.0",
    "gatsby-plugin-image": "^1.1.1",
    "gatsby-plugin-less": "^5.4.0",
    "gatsby-plugin-manifest": "^3.1.0",
    "gatsby-plugin-offline": "^4.1.0",
    "gatsby-plugin-react-helmet": "^4.1.0",
    "gatsby-plugin-sharp": "^3.1.1",
    "gatsby-source-filesystem": "^3.1.0",
    "gatsby-source-strapi": "^1.0.1",
    "gatsby-transformer-sharp": "^3.1.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-bootstrap": "^1.6.0",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "react-markdown": "^6.0.2"
  }
`
Also i tried with gatby-source-strapi@alpha , but didn't worked

the error is exactly same:
 Cannot query field "publicURL" on type "StrapiContactUsContactButtonsLogo"  graphql/template-strings

**Comment by receter** [comment]
I think this is realated to https://github.com/gatsbyjs/gatsby/discussions/4993

You need to add gatsby-source-filesystem to gatsby-config.js even if you don't need it.

For me, adding the following code to `gatsby-config.js` did solve the issue.
```
...
    {
      // We need filesystem source plugin to add publicURL function to File nodes
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `placeholder`,
        // path is required param, so let's just point it to single file to not create
        // much unnecessary work for it
        path: `${__dirname}/gatsby-config.js`,
      }
    },
...
```

Another solution might be using `gatsby-transformer-remote-filesystem` as suggested in the above discussion.
