### ISSUE TITLE
error "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

### ISSUE THREAD

**Issue by Suljam** [strapi/gatsby-source-strapi#167]
Having an issue when adding `gatsby-source-strapi` to my Gatsby site. When I try to run `gatsby develop` it keeps erroring out with:
```
success Fetched Strapi Data - 0.027s
error "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 403
error htmlparser.DomHandler is not a constructor
/Users/sul/Work/Development/sulcalibur/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
```

**Comment by carlos-ch** [comment]
I am also having this error.

**Comment by LukaEHB** [comment]
Try the following:
Go to the Strapi admin panel then enable the following setting:  
Settings>rolles and permissions>users-permissions>user>find

**Comment by DuggalVerse** [comment]
I am facing the same issue and I've already done that.

**Comment by riefer02** [comment]
I just had a similar issue and I went to my Single Types > Home Page > ::clicked publish:: :sweat_smile:

**Comment by zafar633** [comment]
i am tired with gatsby  same error look like this :  "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

**Comment by arif-ali45** [comment]
`ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

connect ECONNREFUSED ::1:1337



  Error: connect ECONNREFUSED ::1:1337

  - node:net:1161 TCPConnectWrap.afterConnect [as oncomplete]
    node:net:1161:16`

Facing same error while gatsby-develop, i have a content type 'jobs' when i develop it throws the error

**Comment by arif-ali45** [comment]
`ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

connect ECONNREFUSED ::1:1337



  Error: connect ECONNREFUSED ::1:1337

  - node:net:1161 TCPConnectWrap.afterConnect [as oncomplete]
    node:net:1161:16`

Facing same error while gatsby-develop, i have a content type 'jobs' when i develop it throws the error

**Comment by elmehdibadaoui** [comment]
same here, the error still exists.


`success compile gatsby files - 0.326s
success load gatsby config - 0.020s
success load plugins - 0.500s
success onPreInit - 0.004s
success initialize cache - 0.196s
success copy gatsby files - 0.069s
success Compiling Gatsby Functions - 0.134s
success onPreBootstrap - 0.148s
success createSchemaCustomization - 0.011s
success Fetched Strapi Data - 0.003s

 ERROR #11321  PLUGIN

"gatsby-source-strapi" threw an error while running the sourceNodes
lifecycle:

Cannot read property 'toLowerCase' of undefined



  TypeError: Cannot read property 'toLowerCase' of undefined
  
  - pluralize.js:136 Function.plural
    [frontend]/[pluralize]/pluralize.js:136:24
  
  - pluralize.js:177 pluralize
    [frontend]/[pluralize]/pluralize.js:177:46
  
  - index.js:26 toTypeInfo
    [frontend]/[gatsby-source-strapi]/lib/index.js:26:79
  
  - Array.map
  
  - index.js:122 Object.exports.sourceNodes
    [frontend]/[gatsby-source-strapi]/lib/index.js:122:59
  
  - api-runner-node.js:462 runAPI
    [frontend]/[gatsby]/src/utils/api-runner-node.js:462:16
  

warn The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you
need it?`

**Comment by kwiat1990** [comment]
> 

For me the reason was missing `.env` file for the production build. I had only `.env.development` and after adding one for production it did worked.

**Comment by Claudiu7672** [comment]
@Jompra, 

Thank you very much! I was struggling for a few hours with this error. I would have never thought to try that.

**Comment by jasonohdz1501** [comment]
@Jompra thanks for your solution. it worked for me

**Comment by everythinginjs** [comment]
same problem here for deployment.


 ERROR #349

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

"gatsby-source-strapi": "2.0.0",
"gatsby": "4.23.1",
