### ISSUE TITLE
The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?

### ISSUE THREAD

**Issue by mikeyfe6** [strapi/gatsby-source-strapi#168]
I have this issue where Gatsby doesn't want to connect to my content-types, before it worked just fine...

```
Cannot query field "allStrapiNegosite" on type "Query".

If you don't expect "allStrapiNegosite" to exist on the type "Query" it is most likely a typo.
However, if you expect "allStrapiNegosite" to exist there are a couple of solutions to common problems:
```

```
{
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: process.env.DEPLOY_URL
          ? "https://negoscan-database.herokuapp.com"
          : "http://localhost:1337",
        contentTypes: [`negosite`, `user`],
        markdownImages: {
          typesToParse: {
            negosite: ["biografie"],
          },
        },
        queryLimit: 1000,
        loginData: {
          identifier: "",
          password: "",
        },
      },
    },
```

someone please tell me whats the problem?

**Comment by searich** [comment]
just happened to me.  postman no problem to  see the json through api endpoint.

**Comment by searich** [comment]
It was network's issue. Fixed .

**Comment by garbanv** [comment]
Hi guys, i had the same problem yesterday when using a singleType and it was solved when click "publish", it was because was not published.  that solved the problem

**Comment by remidej** [comment]
I'm closing this as it doesn't appear to be an issue with the source plugin. This warning usually pops up if:

- you have no data in your Strapi app
- your Strapi app is offline
- you haven't linked your Strapi app correctly in the `gatsby-config.js` file (check your env variables)
- you haven't configured your content types correctly in the `gatsby-config.js` file

Make sure you read the [readme documentation](https://github.com/strapi/gatsby-source-strapi#readme) (for v1+ versions), and please open a new ticket if you find an actual bug
