### ISSUE TITLE
Media Item to Local File

### ISSUE THREAD

**Issue by Ortimis** [strapi/gatsby-source-strapi#174]
When linking to a media file in a markdown text field, it would be nice to have the option that gatsby-source-strapi downloads the file in question, puts it in the static folder and changes the link in the markdown respectively.

This is done, e.g., in https://github.com/gatsbyjs/gatsby-source-wordpress-experimental

Is there any documentation on how to achieve that behaviour? Thank you

**Comment by derekqq** [comment]
Hi @Ortimis,  
I had a similar problem with me using the code from this thread insert it into gatsby-node.js helped.
With this code, an additional publicURL field is created in graphQL and any files are copied to public/static.
https://github.com/gatsbyjs/gatsby/discussions/4993#discussioncomment-114251

Alernative solution is to use the node-fetch library and write code like this. 
`const fetch = require("node-fetch");

exports.onCreateNode = async ({ node, actions, store, cache }) => {
  const { createNode, createNodeField } = actions;
  console.log(node.internal.type);
  if (node.internal.type !== null && node.image !== null) {
    console.log(node.image);

    fetch("http://localhost:1337" + node.image.url).then((res) => {
      const dest = fs.createWriteStream("./static/uploads/" + node.image.name);
      res.body.pipe(dest);
    });
  }
};
`
