### ISSUE TITLE
Schema customization for Sharp images (1.0 Alpha)

### ISSUE THREAD

**Issue by Mites88** [strapi/gatsby-source-strapi#178]
Has anyone tried customizing their graphql schema in order to have optional image fields on their app?

I tried putting this on my gatsby-config, title works fine, image does not.

``` exports.createSchemaCustomization = ({ actions }) => {
  const typeDefs = `
    type strapiArticle implements Node {
      title: String
      image: File
    } `
  createTypes(typeDefs)
}

// My query looks like this:

Query {
  allStrapiArticle {
    title
    image {
      localFile {
        childImageSharp {
          fluid {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  }
}

// I need images to return null instead of breaking my build process if Gatsby can't infer the schema by itself.

**Comment by iksent** [comment]
I have a very similar problem: https://github.com/gatsbyjs/gatsby/issues/29100#issuecomment-775051264

**Comment by iksent** [comment]
It probably works for me now.

Create a new type and use it instead of "File":

```
    type LocalFile {
      localFile: File @link(from: "localFile___NODE")
    }

    type strapiArticle implements Node {
      title: String
      image: LocalFile
    } `
```

@Mites88, Can you check, is it works with childImageSharp?

**Comment by Mites88** [comment]
Thank you for your response, @iksent !

Unfortunately I still can't get it to work with childImageSharp. I tried some combinations of your example and I still get the "dummy content" error.
