### ISSUE TITLE
Plugin does not support publish/draft from strapi

### ISSUE THREAD

**Issue by cempesket** [strapi/gatsby-source-strapi#185]
There is no way to have draft/publish system with gatsby/strapi at the moment.

We need to publicationState=preview option in the configs.

I did it in this [pull request](https://github.com/strapi/gatsby-source-strapi/pull/184)

**Comment by dvakatsiienko** [comment]
This is definitely the feature that should be enabled by default. Please add it to the core!

**Comment by remidej** [comment]
Hello, this is now possible with the new v1 release of the plugin. We provide a new option that allows you to set your API query parameters for each content type. So you can now set `publicationState` as `preview` in your config.

However, this was undocumented, so I opened #217 to add an example to the readme
