### ISSUE TITLE
Cannot query field "childImageSharp" on type sixpack-shop-frontend-gatsby    | "StrapiProductImage"

### ISSUE THREAD

**Issue by ScyDev** [strapi/gatsby-source-strapi#194]
I just switched from `0.0.12` to `alpha` and now I'm getting:
```
/app/gatsby-strapi/src/templates/productTemplate.js
  101:9  error  Cannot query field "childImageSharp" on type
"StrapiProductImage"  graphql/template-strings
```

Any ideas?
If I switch back it works fine again.

**Comment by FredWahlqvistDrop** [comment]
Have you tried in query explorer that childImageSharp is available, believe it now sits under local file or similar.

**Comment by ScyDev** [comment]
That's it! Thanks :)
