### ISSUE TITLE
how to filter the source request 

### ISSUE THREAD

**Issue by GabrielLiade** [strapi/gatsby-source-strapi#195]
Hi everyone,

when I do this 

resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `https://apiUrl`,
        queryLimit: 100, // Default to 100
        contentTypes: [`content`, `article`, `brand-category`],
      },

it will fetched like this : 

info Starting to fetch data from Strapi - https://apiUrl/content/content?_limit=100
info Starting to fetch data from Strapi - https://apiUrl/article/article?_limit=100
info Starting to fetch data from Strapi - https://apiUrl/brand-category/brand-category?_limit=100

But I have actually 1000 records, but if I fetched all of them my server crash

It is possible to fetch data with filter ? in order to get something like this : 

info Starting to fetch data from Strapi - https://apiUrl/content/content?_limit=100&_start=10&_sort=drop_date:'ASC'
info Starting to fetch data from Strapi - https://apiUrl/article/article?_limit=100&_start=10&_sort=drop_date:'ASC'
info Starting to fetch data from Strapi - https://apiUrl/brand-category/brand-category?_limit=100&_start=10&_sort=drop_date:'ASC'

those filter worked already now I want to apply them

**Comment by damiepsz3** [comment]
Hi, you are able to customize the endpoint of each contentType this way: 
```
resolve: gatsby-source-strapi,
options: {
  apiURL: https://apiUrl,
  queryLimit: 100, // Default to 100
  contentTypes: [name: "content", endpoint: "custom-endpoint"], <------- example
},
```

**Comment by remidej** [comment]
Closing in favor of #104
