### ISSUE TITLE
contentTypes containing "-"  used with DynamicZoneFields lead to an error

### ISSUE THREAD

**Issue by olwe0002** [strapi/gatsby-source-strapi#197]
gatsby-config.js:

specify contentType with "-", e.g.  contentTypes: ['blog-post']

then use it in some query:

```
export const query = graphql`
  query BlogPostQuery($slug: String!) {
    strapiBlogPost(slug: { eq: $slug }) {
      some_fields
      dynamic {
        some_more_fields
      }
    }
  }
```

this results in 
```
Missing onError handler for invocation 'building-schema', error was 'Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "StrapiBlog-post" does not.'. Stacktrace was 'GraphQLError: Names
must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "StrapiBlog-post" does not.
    at isValidNameError 
```
with [this](https://github.com/strapi/gatsby-source-strapi/commit/eb0e67a6d6b7828b776f4bbcac3a03b9321aae75#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556) commit the *addDynamicZoneFieldsToSchema* method came in, which causes this error.

**Comment by LukeVibes** [comment]
Having the same issue

**Comment by remidej** [comment]
Dynamic zones are handled differently in the new v1.0.0 ([see the migration guide on our blog post](https://strapi.io/blog/introducing-the-new-gatsby-source-strapi-plugin))

Can you try upgrading to that version and let me know if this still happens?

**Comment by denforlatte** [comment]
I'm getting this on v1.0.1

**Comment by remidej** [comment]
We release v1.0.2 with a fix for this bug thanks to @blurfx
