### ISSUE TITLE
Gatsby throwing an error.

### ISSUE THREAD

**Issue by blonc** [strapi/gatsby-source-strapi#2]
one you load in the plugin and start gatsby it throws the following errors.  

`error Plugin gatsby-source-strapi returned an error

  Error: Request failed with status code 401
  
  - createError.js:16 createError
    [blog-strapi]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:18 settle
    [blog-strapi]/[axios]/lib/core/settle.js:18:12
  
  - http.js:192 IncomingMessage.handleStreamEnd
    [blog-strapi]/[axios]/lib/adapters/http.js:192:11
  
  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11
  
  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
  

warning The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?`

my gatsby-config.js is as followed:

`module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337`,
        contentTypes: [
          // List of the Content Types you want to be able to request from Gatsby.
          `article`,
          `user`,
        ],
      },
    },
  ],
};`

**Comment by mattbag** [comment]
Do you have strapi installed? There's not much information about this here

**Comment by pierreburgy** [comment]
@blonc you have to update the security rules in the Permissions section of the Strapi dashboard: https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/#allowaccess.
