### ISSUE TITLE
error Plugin gatsby-source-strapi returned an error

### ISSUE THREAD

**Issue by jerembardon** [strapi/gatsby-source-strapi#20]
Hi there,

I've followed the tutorial about gatsby and simple articles blog but I have an Issue.

I have this error:

`error Plugin gatsby-source-strapi returned an error

  Error: Request failed with status code 403
  
  - createError.js:16 createError
    [app]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:18 settle
    [app]/[axios]/lib/core/settle.js:18:12
  
  - http.js:192 IncomingMessage.handleStreamEnd
    [app]/[axios]/lib/adapters/http.js:192:11
  
  - next_tick.js:139 _combinedTickCallback
    internal/process/next_tick.js:139:11
  
  - next_tick.js:181 process._tickCallback
    internal/process/next_tick.js:181:9
  
Fetch Strapi data: 53.412ms
[LOADER] source and transform nodes
`

So that comes in when I have modified the file **gatsby-config.js** with the informations provided in documentation and tutorial. The  strapi server start but gatsby fail when I've made the modification.

I have already see in closed issue a guy with the same problem on Gatsby but I don't want to just throw problem away. I'm on MacOS (High Sierra)

Do you have any ideas ? Someone have problem with gatsby install & launch gatsby  on MacOS ?

**Comment by jerembardon** [comment]
Nobody have an idea ? 

Strapi, mongod and mogo are launch but gatsby don't want when I launch the project ...
Do I need to do something in api folder or administration ? Permissions are already set to "find"

**Comment by rouxiaoxiao** [comment]
I have the same problem now..

**Comment by MortezaAghili** [comment]
Same

**Comment by MortezaAghili** [comment]
I found it, Gatsby needs access to find the user.

https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/#allowaccess
