### ISSUE TITLE
Support Gatsby Image in dynamic zones and rich text fields

### ISSUE THREAD

**Issue by tfinlay** [strapi/gatsby-source-strapi#202]
I've been searching for a while, and haven't been able to figure out how to get `gatsby-source-strapi` to provide images that work with Gatsby's sharp system.

I may be missing something obvious, but this is pretty key for me to get figured out! Some up-to-date documentation or any pointers would be much appreciated.

### Details

My page query:
```graphql
query {
    strapiHomePage {
      id
      Banner {
        BubbleLine1
        BubbleLine2
        BubbleLine3
        BubbleLine4
        CustomBannerImage {
          url
          alternativeText
          childImageSharp {
            gatsbyImageData(width: 200)
          }
        }
      }
    }
  }
```

Gatsby build error:
```
There was an error in your GraphQL query:

Cannot query field "childImageSharp" on type "StrapiHomePageBannerCustomBannerImage".

If you don't expect "childImageSharp" to exist on the type "StrapiHomePageBannerCustomBannerImage" it is most likely a typo.
However, if you expect "childImageSharp" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "childImageSharp" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "StrapiHomePageBannerCustomBannerImage":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-definitions
```

Versions:
| package | version |
| -------- | ------- |
| gatsby | ^3.3.1 |
| gatsby-plugin-sharp | ^3.4.0 |
| gatsby-source-strapi | ^1.0.0-alpha.1 |
| gatsby-transformer-sharp | ^3.4.0 |

Thanks!

**Comment by andrestejada** [comment]
I have the same problem

**Comment by torquan** [comment]
I have a similar problem. For some images, the childImageSharp exists, for others it doesn't.
You can check via graphql easily: [http://localhost:8000/___graphql?](http://localhost:8000/___graphql?)

I have one component with three image fields, one of them is shown as type "File" (childImageSharp exists), the others as Strapi[..]Image2 etc. If they are not marked as type "File", childImageSharp will not appear.
I have no clue why this happens, it happens even if I upload the same image to both fields.

**Comment by mannp** [comment]
The same issue for me on v1.0.0 release...

**Comment by zgababa** [comment]
Same thing here, I had to rollback to my previous version: `yarn add gatsby-source-strapi@0.0.12`

**Comment by gastonfl** [comment]
Same issue, nothing in the documentation.
Please help
imagen_fondo {
        childImageSharp {
          gatsbyImageData(
            width: 1920
            placeholder: BLURRED
            formats: [AUTO, WEBP, AVIF]
          )
        }
      }
not working anymore, I already change contentTypes for collectionTypes in gatsby-config.js

**Comment by FredWahlqvistDrop** [comment]
Is this the same issue? 
https://github.com/strapi/gatsby-source-strapi/issues/194
e.g in the update you need to add localFile.

see new documentation on https://github.com/strapi/gatsby-source-strapi

**Comment by gastonfl** [comment]
Already try that instead error with childimagesharp error in localfile

**Comment by notaduck** [comment]
I actually got it to work with `GatsbyImage`

```
export const query = graphql`
  query( $locale: String!){
    strapiLandingpage(locale: {eq: $locale}) {
      id
      Title
      locale
    image {
      id
      localFile {
        childImageSharp {
          fluid {
  ...GatsbyImageSharpFluid
          }
        }
      }
    }
    }
  }
`
```

We just need to get the image data

```js
const component = ({data}) => {
const {strapiLandingpage} = data
    const image = getImage(strapiLandingpage.image?.localFile)
    
    return (
    <>
            <GatsbyImage image={image} alt='asd'/>
    </>
        )
    }
```

However, I have not managed to get it to work with the `<StaticImage>` component, which is crucial if you ask me!

**Comment by notaduck** [comment]
@zgababa I actually tried that, however the `<StaticImage>` does not accept the absolute or relative path prop from the `localFile` :S

**Comment by zgababa** [comment]
@notaduck if I correctly understood  that's normal. Because that's a dynamic image. 

When you use a localFile, you using the CMS, so you using a dynamic image.
`<StaticImage>` is only for images in a folder for example. Never from a CMS like strapi.

I think that the path prop from `childImageSharp` or `localFile` is not like a *real* relative path

**Comment by notaduck** [comment]
@zgababa You are probably right, however, I think it would make the most sense since everything else sourced from Strapi is created at build time. And it is possible with the "old" `<Img ...../>` component to build it statically.

**Comment by blurfx** [comment]
I have the problem. currently, I solved this issue using patch-package to fix dynamic zone not to depend on json type.

But it would be nice if an option to not depend on the dynamic zone as a json type would be added. like:

```js
{
  resolve: 'gatsby-source-strapi',
  options: {
    disableDynamicZoneJsonRely: false,         // any good name ?
    ...
}
```

**Comment by csibivili** [comment]
@blurfx could you please provide your solution?

**Comment by blurfx** [comment]
@csibivili Sure. 

1. Install [patch-package](https://www.npmjs.com/package/patch-package) first. (follow the set-up section in readme)
2. find the code below in `node_modules/gatsby-source-strapi/lib/index.js`
```js
const dynamicZoneFields = {};
items.forEach(item => {
  _lodash.default.forEach(item, (value, field) => {
    if (_normalize.default.isDynamicZone(value)) {
      dynamicZoneFields[field] = 'JSON';
    }
  });
}); // Cast dynamic zone fields to JSON
```

3. comment out the `items.forEach` loop
```js
const dynamicZoneFields = {};
/*
items.forEach(item => {
  _lodash.default.forEach(item, (value, field) => {
    if (_normalize.default.isDynamicZone(value)) {
      dynamicZoneFields[field] = 'JSON';
    }
  });
}); // Cast dynamic zone fields to JSON
*/
```
4. run `yarn patch-package gatsby-source-strapi` and its done.

**Comment by mannp** [comment]
Initially it didn't work for me, but of late I managed to get everything working with the localFile change below.

The rest is just there for context but it does work with the latest versions of gatsby, gatsby image and the strapi data plugin :)
```
      published
      status
      image {
        localFile {
          childImageSharp {
            gatsbyImageData(
              width: 240
              height: 175
              placeholder: BLURRED
              layout: FIXED
              formats: [AUTO, WEBP, AVIF]
            )
          }
        }
      }
```

**Comment by remidej** [comment]
As @mannp said, you should use the localFile key where you'll find all the data you need to use Gatsby Image.

There are 2 cases where we don't handle Gatsby's image processing though:

- In dynamic zone
- In rich text (markdown)

**Comment by MotaZor94** [comment]
Any updates on this one?

**Comment by hungtcs** [comment]
+1

**Comment by jonhue** [comment]
+1

**Comment by RobinSJames** [comment]
I've got a similar situation.
I have an image component in a dynamic zone. I am no longer able to query gatsbyImageData.
This will be the second time that I've had to fork the repo and make my own adjustments to this plugin.

**Comment by yolit-bitlogic** [comment]
Hello, Any solutions to this problem? Now I'm working with a dynamic zone and it doesn't show me gatsbyImageData.
