### ISSUE TITLE
Add empty index.js in the alpha 1.0.0 version

### ISSUE THREAD

**Issue by visualfanatic** [strapi/gatsby-source-strapi#203]
I wanted to try the alpha version, but Gatsby was complaining that it could not find `gatsby-source-strapi` plugin anywhere. This is because there is no `index.js` that Gatsby uses to identify plugins.

**Comment by remidej** [comment]
Hello, please install the plugin through the NPM registry: 

```sh
# Using Yarn
yarn add gatsby-source-strapi

# Or using NPM
npm install --save gatsby-source-strapi
```

The problem shoudn't occur when you do this
