### ISSUE TITLE
Is this library compatible with latest version of Gatsby and Strapi?

### ISSUE THREAD

**Issue by mnlbox** [strapi/gatsby-source-strapi#22]
Hi guys,
Is this library compatible with latest version of Gatsby and Strapi?

**Comment by secretlifeof** [comment]
I can query strapi text items, and get url to images but I am not able to use gatsby-images, gatsby-plugin-sharp, gatsby-transformer-sharp. Maybe I am doing something wrong because I am new to Strapi/Gatsby? That said the plugins are installed and added to gatsby-config.js 😉

**Comment by dorelljames** [comment]
Trying using `yarn` instead of `npm`. I encountered an error with `sharp` of sort of `undefined` at deploy but nonetheless those plugins should work when I use `yarn`.

**Comment by lauriejim** [comment]
@mnlbox I close this issue, it works well with last version of Gatsby.

@dorelljames  I suggest you to use `npm` Strapi is not compatible with `yarn` actually - issues already exist on mono repo.

@gonzochic Update haven't be reverted... It's on  `0.0.6` version.

**Comment by gonzochic** [comment]
@lauriejim 
in the current gatsby master we have a dependency to `"gatsby-source-filesystem": "^1.5.39"` which has a peer dependency on Gatsby < 2

```json
"peerDependencies": {
    "gatsby": "^1.9.250"
  }
```
We would need to upgrade source-filesytem to a new major version. This happened already but has been reverted (see 19c790ad251871d5ccf179b4fa659575ca5abb54)

**Comment by lauriejim** [comment]
Ho okay! I see what you are talking about.
We don't have much time dedicated to that.

I suggest you to submit a PR if you want have this update.
And make sure all the Gatsby tuto works well.

We will appreciate your help on this point.

**Comment by gonzochic** [comment]
@pierreburgy could you give us an insight, why this change was reverted? I could imagine it might break for all people using gatsby v1, or?
