### ISSUE TITLE
Field does not exist error when building schema

### ISSUE THREAD

**Issue by invent-uk** [strapi/gatsby-source-strapi#226]
Since upgrading to 1.0.1 (from 0.0.12) there seem to be issues with the dynamic zones during the building-schema phase. I should add this is using the blurfx fork as the entities include hyphens and it fails earlier without that.

The error is as follows:

`Missing onError handler for invocation 'building-schema', error was 'Error: Cannot get field 'productAttributes' from type 'StrapiProductFilter'.`

Now, the odd thing is that ProductFilter does not contain anything to do with productAttribute. If I comment this type in gatsby-config it fails on an entirely different type that also contains a dynamic zone, again using a field name that should not be associated. 

It feels like there is an off by one error or something similar in the code. Could you provide a quick heads up on the quickest way to diagnose this so that I can provide more info and help get this fixed?

**Comment by invent-uk** [comment]
Having added a log of the types being fed into createTypes() in index.js I can see that createTypes is being called correctly:
}
  name: 'StrapiProduct',
  fields: { productAttributes: 'JSON' },
  interfaces: [ 'Node' ]
}
{
  name: 'StrapiProductFilter',
  fields: { criteria: 'JSON' },
  interfaces: [ 'Node' ]
}

But something later on is causing Gatsby to think that the productAttributes field belongs to ProductFilter.

Changing the order of the collectionTypes in gatsby-config so that the Product is after ProductFilter seems to work around the problem. Any thoughts as to where this might be coming from?

**Comment by remidej** [comment]
Hello, is the field `productAttributes` a dynamic zone or is that another one?

**Comment by invent-uk** [comment]
Hey Rémi,

Product contains a dynamic zone _productAttributes_:

  ```
  "productAttributes": {
      "type": "dynamiczone",
      "components": [
        "attributes.product-attribute"
      ]
    }
```


ProductFlilter contains a dynamic zone _criteria_:
```

    "criteria": {
      "type": "dynamiczone",
      "components": [
        "product.product-filter-criterion-item"
      ]
    }
```

So the error:

`Cannot get field 'productAttributes' from type 'StrapiProductFilter'.
`

Suggests something is causing the iteration to fall out of sequence and the code is expecting a dynamic zone at n+1 to be at n. That's how I read it anyway!
