### ISSUE TITLE
file upload on dynamic zone breaks the response 

### ISSUE THREAD

**Issue by Daro007** [strapi/gatsby-source-strapi#229]
I had a component call "upload" which was only a single media field (only file) and that was connected to my dynamic zone "uploads" as a relational field. 
What happens is that when I do that it changes the response on Gatsby and instead of receiving JSON (as I was receiving so far until creating this field) it changed back to nodes.
Any ideas? any workaround ?

**Comment by remidej** [comment]
Hello, can you please provide a repo or a code sandbox so I can reproduce this problem?
