### ISSUE TITLE
Fetch images from nested Objects / Referenced Ressources

### ISSUE THREAD

**Issue by gonzochic** [strapi/gatsby-source-strapi#23]
I have the following issue: 

Imagine you have two Tables: `Category` and `Product`. In Strapi every Product has a reference to a Category + every product has a `thumbnail` (Image) as well es every Product.

In the scenario that I have a Category Page in Gatsby I would like to fetch all `Product` which are related to the selected `Category`. This works. 

What doesn't work: the `thumbnail` field of the related products is not populated. Well i recognized this is not an Error of this projects. This is just because I have to populate this field in the Strapi Services (see https://github.com/strapi/strapi/issues/1783)

Well, after doing this my a `thumbnail` field was added to the nodes, but it wasn't of type `File` which is need to reference the React code to the local copy of the image. Looking at the part where the Strapi plugin tries to detect if the `MIME` is present and therefore create an `File` type (besides other things) only checks the first level.

```javascript
for (let item of entity) {
        // loop item over fields
        for (const key of Object.keys(item)) {
          const field = item[key]
          // image fields have a mime property among other
          // maybe should find a better test
          if (field !== null && field.hasOwnProperty('mime')) {
           // create a file
          }
     }
}
```

I created a fix to check if there is a relation and run this code also on the related field.

**Comment by dwehrmann** [comment]
@gonzochic Were you able to solve this? I'm having the same problem. My images are displayed fine as long as I reference them with 'http:localhost:1337' but of course break when deploying as they are not downloaded.

**Comment by gonzochic** [comment]
@dwehrmann have you tried my PR #24? Maybe you can post your GraphQL Query. :)

**Comment by dwehrmann** [comment]
@gonzochic Hey, thanks for replying. Yes, I updated /node_modules/gatsby-source-strapi/src/normalize.js with your changes and rebuilt the module but that obviously had no effect. Am I doing something wrong?

My GraphQL query looks like that:

```
  query ReferenzDetail($id: String!) {
    strapiReferenz(id: { eq: $id }) {
      Title
      Ref_Description_Intro
      Ref_Description_Fulltext
      Ref_Leistungen
      Ref_Kunde
      Ref_Fakten
      Ref_Category
      lat
      lon
      zoom
      Ref_Images {
        url           
      }
```

However, it seems to return only the path, not the image itself which would explain why the image is not downloaded from strapi. 

Any help would be greatly appreciated.

**Comment by pierreburgy** [comment]
@dwehrmann here is the configuration you must have to be able to use `childImageSharp`:

```js
// gatsby-config.js
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: 'http://localhost:1337',
        contentTypes: [ // List of the Content Types you want to be able to request from Gatsby.
          'article',
          'user'
        ]
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
      },
    },
    'gatsby-plugin-offline',
  ],
}
```

Example here:

```js
import React from 'react'
import { Link, graphql } from 'gatsby'
import Img from 'gatsby-image'
import Layout from '../components/layout'

const IndexPage = ({ data }) => (
  <Layout>
    <h1>Hi people</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <ul>
      {data.allStrapiArticle.edges.map(document => (
        <li key={document.node.id}>
          <h2>
            <Link to={`/${document.node.id}`}>{document.node.title}</Link>
          </h2>
          <Img fixed={document.node.image.childImageSharp.fixed}/>
          <p>{document.node.content}</p>
        </li>
      ))}
    </ul>
    <Link to="/page-2/">Go to page 2</Link>
  </Layout>
)

export default IndexPage

export const pageQuery = graphql`  
  query IndexQuery {
    allStrapiArticle {
      edges {
        node {
          id
          image {
            childImageSharp {
              fixed(width: 200, height: 125) {
                ...GatsbyImageSharpFixed
              }
            }
          }
          title
          content
        }
      }
    }
  }
`
```

Thanks again @gonzochic for the pull request!

**Comment by gonzochic** [comment]
@dwehrmann i think it is not a good idea to edit the `node_modules` folder

What you need to do is to install the plugin locally (see https://www.gatsbyjs.org/docs/source-plugin-tutorial/#create-a-plugins-folder).

Simply check out the `master` of `strapi-source-plugin` into the plugins folder (and don't forget to remove the one from the node_modules/package.json). I can't remember but I think you have to run `npm run build` inside your local copy of the source-plugin.

**Comment by gonzochic** [comment]
@vasupol11 I think this is the wrong issue for you problem. It might be better located in #8

**Comment by dwehrmann** [comment]
@pierreburgy @gonzochic Thank you both, that helped me.
