### ISSUE TITLE
Singletypes with Locale(s) doesn’t return translations

### ISSUE THREAD

**Issue by notaduck** [strapi/gatsby-source-strapi#230]
Hi There.
I have created a new project with the latest version of gatsby, gatsby-strapi-plugin and strapi itself.

I have added the configuration for strapi to gatsby-config.js

    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337`,
        queryLimit: 1000, // Default to 100
        singleTypes: [
          { 
            name: 'homepage',
            api: { qs: { _locale: `all` } }
           }
        ]
      },
    },

I have a SINGLE TYPE called homepage with a title and localization enabled.
However, querying strapi with graphql only returns the English title and not the other locales which are defined
```
query MyQuery {
  allStrapiHomepage {
    edges {
      node {
        id
        Title
        locale
        localizations {
          locale
        }
      }
    }
  }
}
```
returns:
```
{
  "data": {
    "allStrapiHomepage": {
      "edges": [
        {
          "node": {
            "id": "Homepage_1",
            "Title": "xxx Track Day xxx",
            "locale": "en",
            "localizations": [
              {
                "locale": "da",
              },
              {
                "locale": "sv-SE",

              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {}
}
```
Is this the intended behavior or am I missing something? I

**Comment by themarcus125** [comment]
There's a part about querying locales of singleTypes that you might have missed https://github.com/strapi/gatsby-source-strapi#internationalization-support

Apparently, you can't use `api: { qs: { _locale: `all` } }` to get entries from all locales. 
You have to create singleTypes entity object individually, regarding the locales that the type supports. For instance: 

```
{
  resolve: `gatsby-source-strapi`,
  options: {
    apiURL: `http://localhost:1337`,
    queryLimit: 1000, // Default to 100
    singleTypes: [
      { 
        name: 'homepage',
        api: { qs: { _locale: `en` } }
       },
       { 
        name: 'homepage',
        api: { qs: { _locale: `da` } }
       },
       { 
        name: 'homepage',
        api: { qs: { _locale: `sv-SE` } }
       }
    ]
  },
},

```

**Comment by remidej** [comment]
Thanks for the response @themarcus125, you're exactly right.

I know it's a bit of an awkward solution, but it's one we'll stick to for a while
