### ISSUE TITLE
How to query individual entries?

### ISSUE THREAD

**Issue by impactcolor** [strapi/gatsby-source-strapi#232]
As the question asks I'm attempting to query individual entries where an id is:

`   {
  allStrapiArticle(id: "4") {
    edges {
      node {
        id
        title
        content
      }
    }
  }
}`

`{
  allStrapiArticle {
    edges {
      node(id: "4") {
        id
        title
        content
      }
    }
  }
}`
I tried both of these and neither work.  Any idea how I can accomplish this?

**Comment by themarcus125** [comment]
You should use `filter` instead

```javascript
{
  allStrapiArticle(filter: {id: {eq: "4"}}) {
    edges {
      node {
        id
        title
        content
      }
    }
  }
}
```

For comparing operators, you can refer to this document https://www.gatsbyjs.com/docs/graphql-reference/#filter
