### ISSUE TITLE
Error fetching single type  v1.0.1

### ISSUE THREAD

**Issue by betsyMb** [strapi/gatsby-source-strapi#239]
Hi, 

I created a single type for my site 

![image](https://user-images.githubusercontent.com/74191893/123518072-5542f780-d672-11eb-989f-0f0dda3f93bc.png)

but when I add it to the plugin config for query it returns 403

![image](https://user-images.githubusercontent.com/74191893/123518101-6c81e500-d672-11eb-9ecd-bb8febd0eec6.png)

![image](https://user-images.githubusercontent.com/74191893/123518131-80c5e200-d672-11eb-9700-91dd2df8fbdf.png)

I am using Strapi 3.6.3 and Gatsby 3.6.2 in development mode both

thanks

**Comment by remidej** [comment]
Hello! This is likely not a bug. You should enable the right permissions for the Public role in your Strapi app's settings.

I recommend that you read [our docs about roles & permissions](https://strapi.io/documentation/user-docs/latest/users-roles-permissions/introduction-to-users-roles-permissions.html)
