### ISSUE TITLE
Allow to use old behavior of dynamic zones

### ISSUE THREAD

**Issue by SrJuggernaut** [strapi/gatsby-source-strapi#240]
when it is necessary to use dynamic zones with images, these cannot be easily rewritten to use as 'LocalFiles', perhaps there could be an option in "gatsby-config.js" that allows you what behavior you prefer it to have. The configuration could be used like this:

~~~js
    {
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: process.env.STRAPI_HOST,
        dynamicZones: 'fragments', //default to Json
        collectionTypes: ['user', 'post', 'category'],
        singleTypes: ['home', 'contact']
      }
    },
~~~

**Comment by tizzKraked** [comment]
This is a really big deal for me. Firstly the use of JSON for dynamic zones totally breaks GatsbyImage and secondly I often want to specifically type the response I get from GraphQL, surely that the whole reason .... get what you want when you want it.  Not being able to specify the response fields and getting everything in one JSON object surely pushes up the size of the cached gatsby JSON files by a huge amount.

**Comment by SrJuggernaut** [comment]
In my fork I am trying a solution to this problem [SrJuggernaut/gatsby-source-strapi](https://github.com/SrJuggernaut/gatsby-source-strapi)

**Comment by SrJuggernaut** [comment]
Currently im creating a different plugin with better schema creation for strapi  [SrJuggernaut /
gatsby-source-strapi-schema ](https://github.com/SrJuggernaut/gatsby-source-strapi-schema)

**Comment by remidej** [comment]
Hello and thanks for raising this issue.

We are very aware of the tradeoffs of the current approach ([see my detailed answer there](https://github.com/strapi/gatsby-source-strapi/issues/191#issuecomment-846007145)). As I said there, we'll keep our current solution until we can fully rebuild it on the V2 in a few months.

If you want to keep the old behavior for now, feel free to use an older version or to fork the repo
