### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by siemen-subbaiah** [strapi/gatsby-source-strapi#251]
I have cloudinary setup in strapi and I have uploaded videos from strapi to the media library!
I'm using gatsby-source-strapi plugin to source data from strapi to gatsby.
And whenever I run `gatsby develop` I get the following `EPERM: operation not permitted` error : 

C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: EPERM: operation not permitted, lstat 'C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\.cache\caches\gatsby-source-strapi\tmp-ce7537293d8d0c96b46991b53b1d5cc5.mp4'
    at Object.lstatSync (fs.js:1077:3)
    at Object.lstatSync (C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\graceful-fs\polyfills.js:312:16)
    at Object.rimrafSync (C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\fs-extra\lib\remove\rimraf.js:237:18)
    at WriteStream.<anonymous> (C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\gatsby-core-utils\dist\fetch-remote-file.js:107:26)
    at WriteStream.emit (events.js:327:22)
    at finish (_stream_writable.js:657:10)
    at finishMaybe (_stream_writable.js:644:9)
    at _stream_writable.js:617:7
    at WriteStream._final (internal/fs/streams.js:355:3)
    at callFinal (_stream_writable.js:610:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4048,
  syscall: 'lstat',
  code: 'EPERM',
  path: 'C:\\Users\\Asus\\VSCodeProjects\\fiverr-projects\\goldenwave-frontend\\.cache\\caches\\gatsby-source-strapi\\tmp-ce7537293d8d0c96b46991b53b1d5cc5.mp4'
}

I would love to get a work around for this!

**Comment by codebucks27** [comment]
> I have cloudinary setup in strapi and I have uploaded videos from strapi to the media library! I'm using gatsby-source-strapi plugin to source data from strapi to gatsby. And whenever I run `gatsby develop` I get the following `EPERM: operation not permitted` error :
> 
> C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53 throw ex; ^
> 
> Error: EPERM: operation not permitted, lstat 'C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend.cache\caches\gatsby-source-strapi\tmp-ce7537293d8d0c96b46991b53b1d5cc5.mp4' at Object.lstatSync (fs.js:1077:3) at Object.lstatSync (C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\graceful-fs\polyfills.js:312:16) at Object.rimrafSync (C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\fs-extra\lib\remove\rimraf.js:237:18) at WriteStream. (C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\node_modules\gatsby-core-utils\dist\fetch-remote-file.js:107:26) at WriteStream.emit (events.js:327:22) at finish (_stream_writable.js:657:10) at finishMaybe (_stream_writable.js:644:9) at _stream_writable.js:617:7 at WriteStream._final (internal/fs/streams.js:355:3) at callFinal (_stream_writable.js:610:10) at processTicksAndRejections (internal/process/task_queues.js:80:21) { errno: -4048, syscall: 'lstat', code: 'EPERM', path: 'C:\Users\Asus\VSCodeProjects\fiverr-projects\goldenwave-frontend\.cache\caches\gatsby-source-strapi\tmp-ce7537293d8d0c96b46991b53b1d5cc5.mp4' }
> 
> I would love to get a work around for this!

Hey Did you find any solution for this😥?

I tried many solutions but didn't work.

**Comment by apatel369** [comment]
I am having the same issue after upgrading gatsby-source-strapi from 0.0.12 to 1.0.3. Gatsby clean does, reinstalling node modules does not fix my issue.

**Comment by codebucks27** [comment]
> I am having the same issue after upgrading gatsby-source-strapi from 0.0.12 to 1.0.2. Gatsby clean does, reinstalling node modules does not fix my issue.

Due to this issue, I have deleted all the images and trued few images at a time and sometimes it's working I don't understand what is the issue. (Probably with uploader)

**Comment by LukeVibes** [comment]
I am having the same issue- Gatsby clean does nothing, reinstalling node modules does nothing, this is incredibly frustrating- looking for any help please

**Comment by codebucks27** [comment]
I ended up installing WSL (windows subsystem for linux). Using WSL you can run linux in windows without installing separate OS. 
You have to install nodeJS into the WSL.
I have cloned repo in linux and now it's working without any issue.

I think this issue happening only in windows.
Still if you face this issue in any other OS then you can try to tweak these variables
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem#troubleshooting

**Comment by Hasnain-110** [comment]
Im am facing same issue 
![image](https://user-images.githubusercontent.com/81685621/177931653-e1df4584-dea5-487f-8a05-3cd380df8c27.png)
#
