### ISSUE TITLE
Gatsby fails to build with when JSON is return from dynamic components or rich text fields

### ISSUE THREAD

**Issue by Notaduck** [strapi/gatsby-source-strapi#256]
Hi There.
I am trying to migrate from v3.x => v4.x and the only package which is stopping met is `gatsby-source -strapi`.

It seems like it doesn't like the dynamic components and rich text as well.

```js
There was an error in your GraphQL query:

Field "MenuItems" of type "[StrapiHeaderMenuItems]" must have a selection of subfields. Did you mean "MenuItems { ... }"?

   1 | query staticUsersdanielProjectstrackdayFlowfrondtendNewsrccomponentsheaderheaderTsx1419656663 {
   2 |   allStrapiHeader {
   3 |     nodes {
   4 |       strapiId
   5 |       locale
>  6 |       MenuItems
     |       ^
   7 |       UserMenu {
   8 |         MenuItem {
   9 |           id
  10 |           label
  11 |           slug
  12 |         }
  13 |       }
  14 |       Logo {
  15 |         localFile {
  16 |           childImageSharp {

File path: /Users/daniel/Projects/trackday_flow/frondtend_new/src/components/header/header.tsx
Plugin: none
```

**Comment by AntonKL** [comment]
+1 on same problem with dynamic components on gatsby 4

**Comment by nico-k3** [comment]
Yep, same here. `gatsby develop` works fine, but `gatsby build` returns the exact error you're pointing out.

**Comment by peterfortuin** [comment]
Some problem here. 

Don't really understand why there is a difference between `develop` and `build`. During `develop` it's just a json type, but during `build` there is a dynamic generated type based on the dynamic components. But because we don't see that during `develop`, we have no clue how this looks like (the graphql interface is not helping us here). 

I saw there is a branch where there is some work done towards gettings it to work with Gatsby 4, but I think that's not finished yet. I also have no idea how to test that branch into my Gatsby site. If there is anything I can do to help out, to let me know.

**Comment by peterfortuin** [comment]
Same as #252 btw.

**Comment by Notaduck** [comment]
That was also what I saw @peterfortuin, it would be nice to see a contributer from the Strapi team to come with a response.
Otherwise I might think we would have to choose another CMS at our company.

**Comment by chakerben** [comment]
+1 on same problem with dynamic components

**Comment by au-re** [comment]
did anyone find a workaround to this issue?

**Comment by Notaduck** [comment]
> did anyone find a workaround to this issue?

I do not think so.

**Comment by chakerben** [comment]
I solved this issue by using gatsby 4.3.0-next.1

**Comment by AntonKL** [comment]
For me it didn't help to go for gatsby@4.3.0-next.2. Same error.

**Comment by Notaduck** [comment]
> For me it didn't help to go for gatsby@4.3.0-next.2. Same error.

I can fonfirm that @chakerben's suggestion also fixed the issue for me.
What error do you get?

**Comment by umbrella-yuri-makarenko** [comment]
Hi, I use Gatsby 4.3.0-next.1
Issue with `gasby build` still here. When I run build process I catch this:

```
 GraphQLError: Field "content" of type "[StrapiSolutionContent]" must have a selection of subfields. Did you mean "content { ... }"?
```
did anyone find any workaround to this issue?

**Comment by umbrella-yuri-makarenko** [comment]
> For me it didn't help to go for gatsby@4.3.0-next.2. Same error.

@AntonKL Did you solve the problem?

I've been sitting for 6 hours picking at the sources and no result :(

**Comment by au-re** [comment]
I tried upgrading Gatsby (gatsby@4.3.0-next.1 and gatsby@4.4.0-next.0)  but I get the same error when I run `gatsby build`.. and  the solution in #257 didn't work for me :( 

`GraphQLError: Field "links" of type "[StrapiHeaderLinks]" must have a selection of subfields. Did you mean "links { ... }"?`

**Comment by AntonKL** [comment]
> > For me it didn't help to go for gatsby@4.3.0-next.2. Same error.
> 
> @AntonKL Did you solve the problem?
> 
> I've been sitting for 6 hours picking at the sources and no result :(

Negative. It always a _must have a selection of subfields_ in build.

**Comment by marceligrabowski** [comment]
Hello,

It looks like build with dynamic components as JSON is working again with my proposition of changes (#258)

I don't know when someone will take a look at my PR so I created branch in my fork so you could install it straight from github repo
`npm install marceligrabowski/gatsby-source-strapi#v4_prepublish`

Small warning - install process can take a while, as it builds library while doing npm install

I hope it helps!

Cheers,
Marceli

**Comment by ptimson** [comment]
@marceligrabowski I'm trying to use your fork with gatsby 4 (`4.3.0-next.1`) and strapi 3. But I'm getting on develop or build:

```
Error in "...node_modules/gatsby-source-strapi/gatsby-node.js": Cannot find module './lib'
```

I've looked at your PR but it doesn't seem like anything obvious. Any ideas?

**Comment by ptimson** [comment]
I'm using Gatsby `4.3.0-next.1` and Strapi v3. I can't go to Strap v4 as need MongoDB support.

I've tried making changes to `normalize.js` as in @marceligrabowski https://github.com/strapi/gatsby-source-strapi/pull/258/files#diff-7f7c0e0d6a9d315240bed1f927d895f579dd0ff44188355588383be7ce26574d

No luck just get the same issue:

```
GraphQLError: Field "items" of type "[StrapiTestItems]" must have a selection of subfields. Did you mean "items { ... }"?
```

**Comment by AFXcrush** [comment]
> I'm using Gatsby `4.3.0-next.1` and Strapi v3. I can't go to Strap v4 as need MongoDB support.
> 
> I've tried making changes to `normalize.js` as in @marceligrabowski https://github.com/strapi/gatsby-source-strapi/pull/258/files#diff-7f7c0e0d6a9d315240bed1f927d895f579dd0ff44188355588383be7ce26574d
> 
> No luck just get the same issue:
> 
> ```
> GraphQLError: Field "items" of type "[StrapiTestItems]" must have a selection of subfields. Did you mean "items { ... }"?
> ```

I'm also using Strapi V3 and Gatsby v4 and having the same problem... Did you find a solution?
