### ISSUE TITLE
Multiple strapi - I can use two strapi at the same time

### ISSUE THREAD

**Issue by willydavid1** [strapi/gatsby-source-strapi#264]
I'd like to know if it's possible to use two strapis with different urls at the same time in the same project?

Is it correct to do something like this?

```
// gatsby-config.js
{
    resolve: `gatsby-source-strapi`,
    options: {
      apiURL: 1,
      queryLimit: ____,
      collectionTypes: [
        {
          name: `___`,
          endpoint: `_____`,
        },
        {
          name: `___`,
          endpoint: `_____`,
        },
      ],
    },
  },
{
    resolve: `gatsby-source-strapi`,
    options: {
      apiURL: 2,
      queryLimit: ____,
      collectionTypes: [
        {
          name: `___`,
          endpoint: `_____`,
        },
      ],
    },
  },
```

**Comment by turq84** [comment]
@willydavid1 Did you ever get this resolved? I'm dealing with the same situation.

**Comment by willydavid1** [comment]
@turq84 I solved it by making a custom request from gatsby node

https://egghead.io/lessons/gatsby-request-data-from-a-custom-api-endpoint-to-source-nodes-in-gatsby-with-gatsby-node-js
