### ISSUE TITLE
Doesn't with strapi 4

### ISSUE THREAD

**Issue by Ajell** [strapi/gatsby-source-strapi#270]
Hello,
an error appears even after  giving **permissions** :

{"data":null,"error":{"status":404,"name":"NotFoundError","message":"**Not Found"**,"details":{}}}

 in the console:

Failed to load resource: the server responded with a status of **404 (Not Found)**

or

**my-single-types** :1 GET http://localhost:1337/my-single-types 404 (Not Found)

**Comment by Yuan0100** [comment]
I think it is because the api url is http://localhost:1337/api/my-single-types.

You can check the url in the settings:
![strapi](https://user-images.githubusercontent.com/85390677/151688995-5f4a8a13-fd1d-4076-9bcb-f9f820b992ee.png)

**Comment by remidej** [comment]
We're aware that the current version of this package (1.0.2) doesn't support Strapi v4. We are currently working on it for an upcoming 2.0.0 release.

In the meantime, you can use Strapi v3, or Strapi v4 with the GraphQL source plugin.
