### ISSUE TITLE
Request failed with status code 500 - Stitcher

### ISSUE THREAD

**Issue by ArielMunafo** [strapi/gatsby-source-strapi#271]
This is my feed
https://iusedtobe.castos.com/feed

**Comment by ArielMunafo** [comment]
Why it is closed?

**Comment by remidej** [comment]
You haven't provided any context, like what you were trying to do, when the error happened, what version you're using, etc. And only submitting a link, which doesn't look at all like a Strapi response, makes this issue look like spam
