### ISSUE TITLE
Is there a workaround to still use Strapi v4 for createPages with Gatsby v4 like with RESTAPI's

### ISSUE THREAD

**Issue by mikeyfe6** [strapi/gatsby-source-strapi#272]
Is there a workaround to still use Strapi v4 for createPages with Gatsby v4 like with RESTAPI's

**Comment by remidej** [comment]
It will be possible once with the next major release that will add Strapi v4 support. If you need it right now, you can use gatsby-source-graphql and install the graphql plugin in Strapi

**Comment by mikeyfe6** [comment]
Thanks @remidej, I went for the REST approach.. Will wait for the update thoo, for now i'm OK!

> It will be possible once with the next major release that will add Strapi v4 support. If you need it right now, you can use gatsby-source-graphql and install the graphql plugin in Strapi
