### ISSUE TITLE
plugin doesn't work with postgress?

### ISSUE THREAD

**Issue by muscaiu** [strapi/gatsby-source-strapi#296]
I changed db from `sqlLite` to `postgresql` and the plugin stopped working.

These are my configs:

Front-End:    "gatsby": "2.21.0",
Back-End:     "strapi": "3.3.4",

database.js

```
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "postgres",
        host: env("DATABASE_HOST", "localhost"),
        port: env.int("DATABASE_PORT", 5432),
        database: env("DATABASE_NAME", "portofolio"),
        username: env("DATABASE_USERNAME", "postgres"),
        password: env("DATABASE_PASSWORD", ""),
        schema: env("DATABASE_SCHEMA", "public"),
      },
      options: {},
    },
  },
})

```

gatsby-config.js
```
  {
    resolve: `gatsby-source-strapi`,
    options: {
      apiURL: `http://localhost:1337`,
      queryLimit: 1000, // Default to 100
      singleTypes: [`about`],
      contentTypes: [`jobs`, "projects", "blogs"],
      // singleTypes: [],
    },
  },
```

**Comment by remidej** [comment]
This source plugin should not affected by what database Strapi uses under the hood.

I think what happened is that when you changed your database, your data was wiped, since you had a new empty database. But Strapi needs existing content to define which nodes to create in the Gatsby data layer. So if your collection types have no entries, or if some optional fields are never defined, then gatsby-source-strapi won't know about them, and you'll get errors.

What I recommend is to create content in your Strapi admin first, then restart your Gatsby app

**Comment by muscaiu** [comment]
Sounds like it could work! Thanks!

**Comment by muscaiu** [comment]
I re-added content in the DB after i switched to postgres.  
But it still fails....

<img width="1440" alt="Screenshot 2022-03-10 at 22 06 02" src="https://user-images.githubusercontent.com/11426309/157746125-ae949a85-bfc8-4ca1-9a24-176960fff0c5.png">

<img width="1440" alt="Screenshot 2022-03-10 at 22 06 09" src="https://user-images.githubusercontent.com/11426309/157746132-d5459732-a176-4915-8b2d-ea96af378eb3.png">

<img width="1440" alt="Screenshot 2022-03-10 at 22 06 31" src="https://user-images.githubusercontent.com/11426309/157746142-34e0893f-bfd1-4f48-82af-2fcf4e7816bf.png">

**Comment by muscaiu** [comment]
I followed this tutorial: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html#_6-install-the-pg-node-module

Could the connection string have anything to do with it?

**Comment by muscaiu** [comment]
After a week i realized i have an issue with the `jobs` collection. When i try to look at the data, the collection hangs. Removing it fixes most of the issues, however, if i try create it again, the same issues happens.   
Anyway issue plugin issue is fixed.
