### ISSUE TITLE
error key.includes is not a function when field type is integer

### ISSUE THREAD

**Issue by vasupol11** [strapi/gatsby-source-strapi#30]
I create field integer for my content 
{
height: 50,
width: 40
}

and get the following error thrown when run gatsby develop:
error key.includes is not a function
TypeError: key.includes is not a function

removing the field integers remove the error

**Comment by lauriejim** [comment]
Hello @vasupol11.

Can you give us the full error message please.

And well format your message please.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
