### ISSUE TITLE
heroku deployed strapi using postgres addon: api token needs to be reset on each build

### ISSUE THREAD

**Issue by mark-tanser** [strapi/gatsby-source-strapi#301]
There is a problem with the api token needing to be reset on each rebuild, which is not practical for production. Is this a known issue?

**Comment by mark-tanser** [comment]
This is happening the same with a Digital Ocean deployment, using a Postgres database

**Comment by remidej** [comment]
Hello, please don't create several issues for the same thing. I'll close this and reopen #298 instead
