### ISSUE TITLE
Faster builds for image CDNs

### ISSUE THREAD

**Issue by tylerpaige** [strapi/gatsby-source-strapi#305]
Hi all, thanks so much for the beautifully written gatsby plugin. It's been a really great experience building out a Gatsby site thanks to your hard work.

I'm writing to request a feature that this source plugin provide options for how to deal with a CDN like Cloudinary or S3.

For example, Strapi works well with the `provider-upload-cloudinary` plugin. It records the image's URL, public ID, width, height, etc. With all of this information, there is no need to download the image asset itself. Since I am using a service that provides me with on-the-fly image transformations, I do not need to use Sharp to process a responsive image. In this scenario, downloading the image costs me extra money on bandwidth and it slows down my build time.

Ordinarily this wouldn't really be a problem, but I am working on a site that has about 2000 hi-res images, and the costs are becoming prohibitive.

I would love to see an option in this plugin so that I can avoid images being downloaded in the build process. Maybe it uses strapi's `provider_metadata`?

Or, better yet, if there is a way to get closer to my desired outcome with the existing plugin, I would happily receive your advice. 

Many thanks,
Tyler

**Comment by soupette** [comment]
@tylerpaige we can surely add an option to disable image processing, if you are interested maybe you could open a PR?

**Comment by remidej** [comment]
Closed via #320. You can expect a pre-release soon
