### ISSUE TITLE
TotalCount is always equal to 1

### ISSUE THREAD

**Issue by tomwilson2** [strapi/gatsby-source-strapi#307]
I've encountered an issue where `TotalCount` always equals `1`.
 
My query at `__graphql`.
```
query MyQuery {
  allStrapiWork {
    totalCount
    pageInfo {
      totalCount
    }
  }
}
```

My plugins configuration at `gatsby-config.js`.
```
{
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337`,
        queryLimit: 1000,
        collectionTypes: [{
          name: "work",
          endpoint: "api/works",
        }]
      },
    },
```

**Comment by kicocisco** [comment]
Hey tom, are you using this with v4?

**Comment by kicocisco** [comment]
@tomwilson2 Are you using v4?

**Comment by tomwilson2** [comment]
Yeah, Gatsby4 and Strapi4.

**Comment by remidej** [comment]
I looks to me like you're using v1 of this plugin with Strapi v4, which is not supported. Can you confirm if that's the case?

For Strapi v4 support, please use version 2.x.x of this source plugin instead (latest is the [beta.0](https://www.npmjs.com/package/gatsby-source-strapi/v/2.0.0-beta.0)
