### ISSUE TITLE
Help with media in component

### ISSUE THREAD

**Issue by jasewarner** [strapi/gatsby-source-strapi#315]
Hi there,

Looking for some help, as I haven't been able to get any further with fetching an image from a component.
I'm using `gatsby-source-strapi` v2.0.0 in combination with `@strapi/strapi` v4.1.5.

My "SEO" component has two text fields and an image one.
In GraphQL, whilst I can see the `Title` and `Description` fields, I do not see anything for the `Image` field.

Can somebody point me in the right direction?

Thanks

**Comment by remidej** [comment]
Hello Jase

It looks like your content structure is several levels deep: Content type > seo component > image

So you have a relationship in a relationship. You'll need to set the your content type's population accordingly. Here are a couple links that can help you:

- [Population v4 API docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population)
- [How to set population in gatsby-source-strapi](https://github.com/strapi/gatsby-source-strapi#deep-queries-populate)

Please let me know if that fixes your issue

**Comment by imranDev20** [comment]
@jasewarner Hello Jase, if you have managed to make it work. Can you help me?
