### ISSUE TITLE
gatsby-source-strapi Request failed with status code 403

### ISSUE THREAD

**Issue by Ayesha1212** [strapi/gatsby-source-strapi#322]
The routes are publicly are available and working fine while i am using them as a Restful api but graphlq source strapi throwing this error

Here is the error in terminal

"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 403

  Error: Request failed with status code 403
  
  - createError.js:16 createError
    [hecke]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:17 settle
    [hecke]/[axios]/lib/core/settle.js:17:12
  
  - http.js:293 IncomingMessage.handleStreamEnd
    [hecke]/[axios]/lib/adapters/http.js:293:11
  
  - node:events:539 IncomingMessage.emit
    node:events:539:35
  
  - readable:1345 endReadableNT
    node:internal/streams/readable:1345:12
  
  - task_queues:83 processTicksAndRejections
    node:internal/process/task_queues:83:21`  

 `

here is my package.json file dependencies.

    `"dependencies": {
        "gatsby": "^4.13.0",
        "gatsby-plugin-image": "^2.13.0",
        "gatsby-plugin-react-helmet": "^5.13.0",
        "gatsby-plugin-sharp": "^4.13.0",
        "gatsby-source-filesystem": "^4.13.0",
        "gatsby-source-strapi": "^1.0.3",
        "gatsby-transformer-sharp": "^4.13.0",
        "react": "^17.0.1",
        "react-dom": "^17.0.1",
        "react-helmet": "^6.1.0",
        "react-icons": "^4.3.1",
        "react-modern-drawer": "^1.1.1"
  },`

**Comment by leasytime** [comment]
Seems that you don't have access, which probably means that you dont have the API token configured (or it has expired).

Please confirm that you have created the API token in accordance with below docs:

https://www.gatsbyjs.com/plugins/gatsby-source-strapi/
https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/api-tokens.html

**Comment by TDP17** [comment]
Make sure your access token has full access, this solved the same issue I had a few days ago
![image](https://user-images.githubusercontent.com/71214045/167268237-5a2433c5-5400-4685-89ca-9c3ecbc94acb.png)

Also in Users > USERS & PERMISSIONS PLUGIN > Roles > Public check find and findOne options
![image](https://user-images.githubusercontent.com/71214045/167268291-ad3654f1-2821-4a3a-a2be-b37ab8fc1225.png)

**Comment by remidej** [comment]
As @TDP17 said, please add a full-access API token token to your gatsby-config file.

Having the routes publicly available does not make a difference for this new version of gatsby-source-strapi, we now rely on API tokens instead
