### ISSUE TITLE
Build (and Develop) fails randomly (ECONNRESET)

### ISSUE THREAD

**Issue by barthofu** [strapi/gatsby-source-strapi#324]
## The error

The error happens during the build just after fetching the data from Strapi.
It is relatively random, and can take several shapes (also randomly):

- Error 500 (internal server) :
``` 
error "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:
Request failed with status code 500
  Error: Request failed with status code 500
  
  - createError.js:16 createError
    [site-static]/[gatsby-source-strapi]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:17 settle
    [site-static]/[gatsby-source-strapi]/[axios]/lib/core/settle.js:17:12
  
  - http.js:293 IncomingMessage.handleStreamEnd
    [site-static]/[gatsby-source-strapi]/[axios]/lib/adapters/http.js:293:11
  
  - readable.js:1334 endReadableNT
    internal/streams/readable.js:1334:12
  
  - task_queues.js:82 processTicksAndRejections
    internal/process/task_queues.js:82:21
```

- ECONNRESET
```
error "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:
read ECONNRESET
  Error: read ECONNRESET
  
  - stream_base_commons.js:209 TLSWrap.onStreamRead
    internal/stream_base_commons.js:209:20
```

- Socket
```
error "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:
Client network socket disconnected before secure TLS connection was established
  Error: Client network socket disconnected before secure TLS connection was est  ablished
  
  - errors.js:639 connResetException
    internal/errors.js:639:14
  
  - readable.js:1334 endReadableNT
    internal/streams/readable.js:1334:12
  
  - task_queues.js:82 processTicksAndRejections
    internal/process/task_queues.js:82:21
```

## Comments

- The error started from one day to the next and i haven't even touched my code base in between.
- My server strapi doesn't seems to be the problem. I monitored the performances during the fetching of the plugin it is all normal and there is a lot of RAM/CPU available, and there is nothing both in Strapi and NGINX logs.
- Tried with both dev and prod mode of Strapi.
- When I chain the builds they all fail, but if there is a small pause (undetermined) since the last fail, it will often succeed.
- The errors seem to mean that there is a problem on the side of the Strapi server, except that after various tests, the admin panel is well functional as well as the API endpoints (tested with POSTMAN) at the time (just before or just after) when the error on the Gatsby build occurs.
- Seems to occur way more often on my gitlab runner than on my Windows 10 dev environment.
- UPDATE: the errors don't occur at all on my Windows 10 environment, but only on Linux ones (Gitlab Runner and I tested it on my VPS -> the ECONNRESET error happened at the first build)

## Requirements

- `node.js`: 14.19.1
- `gatsby`: 4.5.3
- `gatsby-source-strapi`: 2.0.0
- `strapi`: 4.1.9
- `sqlite3` as database for my strapi app

**Comment by MRDRMUFN** [comment]
Try updating your Gatsby to 4.13.1 or later there was a race condition that caused connection reset error occuring during single threaded builds like Gitlab runner or Netlify.

**Comment by MRDRMUFN** [comment]
Any chance you mind reporting what optimization you made to NGINX?

**Comment by mikevanis** [comment]
Ditto, I have the exact same problem. @barthofu what did you do on the nginx side to fix this?

**Comment by mikevanis** [comment]
Ok, I think I figured out what the problem was on my setup. I noticed that when the build was crashing, this would come up on the nginx logs:

```
20:08:10 [alert] 10#10: *3768 512 worker_connections are not enough while connecting to upstream, client: 185.238.218.62, server: greenclub.world, request: "GET /api/upload/files?filters[url]=/uploads/07_Placement_of_LED_long_leg_positive_cb743dbd1b.JPG HTTP/1.1", upstream: "http://172.18.0.4:1337/api/upload/files?filters[url]=/uploads/07_Placement_of_LED_long_leg_positive_cb743dbd1b.JPG", host: "greenclub.world:1337"
```

I increased `worker_connections` in my nginx.conf like this:
```
events {
  worker_connections 2048;
}
```

Clearly gatsby build was requesting all my images at the same time (I have about 500), and the worker ran out of connections. Increasing the number of connections did the trick. @MRDRMUFN I hope this helps you <3
