### ISSUE TITLE
How to update data in gatsby?

### ISSUE THREAD

**Issue by Dogtiti** [strapi/gatsby-source-strapi#34]
* Node.js version:10.13.0
* npm version:6.4.1
* Database: Mongodb v3.6.4
* Operation system : MacOS 10.14.1

Now,I hace successfully build my website(or blog) using `strapi、gatsby、gatsby-source-strapi`， ,the quesition is when I update data in strapi,I must rebuild gatsby to see the modification.I want to know how to rebuild it automatically without rebuilding gatsby by `gatsby develop`.

I also read [this](https://strapi.io/documentation/3.x.x/guides/webhooks.html),but It doesn't work

So,is there any details for it? I need some help

**Comment by mabhub** [comment]
_Please anyone correct me if I'm wrong:_

Gatsby is a Static Site Generator so you **have to** rebuild it with `gatsby build` to update your generated site when tour data change.

Although, there are many ways to automatically trigger the rebuild.
For example, webhooks, git hooks. These hooks would have to be handled by your building environment.

**Comment by Dogtiti** [comment]
@mabhub  thanks for your explanation, I have already realized it. And now I use webhook to rebuild it!

**Comment by nero2009** [comment]
Hi @Dogtiti can you please share a github gist / code on how you implemented the webhook

**Comment by Dogtiti** [comment]
@nero2009 Did you mean how to add webhook in strapi?

**Comment by nero2009** [comment]
@Dogtiti yes

**Comment by Dogtiti** [comment]
@nero2009 you can read the [Strapi Documentation](https://strapi.io/documentation/3.x.x/guides/webhooks.html) first.
And I will simply talk about my approach, it may not be the best.
In `api` you may have the follow folders:
![image](https://user-images.githubusercontent.com/38354472/51800422-51c0a180-2269-11e9-8c77-30d1b38516a3.png)
open the `models/xx.js` folder,you'll see it:
![image](https://user-images.githubusercontent.com/38354472/51800447-b67bfc00-2269-11e9-98d9-1571b21fd7d9.png)
And you can write a `shell script` and use nodeJS's [execFile](https://nodejs.org/api/child_process.html) to run the `shell script`,and in the `shell`, you can write about how to rebuild the `gatsby`
