### ISSUE TITLE
image from strapi component doesn't show up in graphql

### ISSUE THREAD

**Issue by sanjipun** [strapi/gatsby-source-strapi#340]
I have custom SEO component which contains metatitle, metadescription and metaimage fields.
![image](https://user-images.githubusercontent.com/64313011/180924007-a1ae10fb-b459-4116-97ec-61d2127232db.png)

Problem:
metatitle and metadescription is showing up in gatsby graphql query but metaimage is not showing up.
![image](https://user-images.githubusercontent.com/64313011/180924147-4a594890-a1f0-4f29-b7d5-fac9b411178c.png)

Expected behaviour:
Show metaimage in graphql query.

**Comment by kalwas123** [comment]
How your gatsby-config.js looks?

**Comment by SGiumelli** [comment]
@sanjipun have you read and used this https://github.com/strapi/gatsby-source-strapi#deep-queries-populate

**Comment by kraiwich-k** [comment]
If depends on @sanjipun's component. How should populate structure look like?

**Comment by charanjit-singh** [comment]
Finally: https://market.strapi.io/plugins/strapi-plugin-populate-deep
