### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by dwehrmann** [strapi/gatsby-source-strapi#39]
Following the codestack-blog example (https://medium.freecodecamp.org/how-to-build-a-react-and-gatsby-powered-blog-in-about-10-minutes-625c35c06481)  I have added some new fields in the strapi content type manager, restarted the strapi server and now I'm getting the following error(s) when running `gatsby develop`:

`error Plugin gatsby-source-strapi returned an error:`

 `TypeError: Cannot read property 'hasOwnProperty' of null`

 `- normalize.js:84 _callee$`
`    [codestack-blog]/[gatsby-source-strapi]/normalize.js:84:36`

` - next_tick.js:131 _combinedTickCallback`
`    internal/process/next_tick.js:131:7`

`  - next_tick.js:180 process._tickCallback`
`    internal/process/next_tick.js:180:9` 

This persists until I remove the fields in the content manager again and restart the server.

Any help / ideas? Empty fields should not throw an error, right?

**Comment by dwehrmann** [comment]
btw, I'm on strapi 3.0.0-alpha.13.0.1

**Comment by lauriejim** [comment]
Please quand you test with last version of Strapi

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
