### ISSUE TITLE
How to add Markdown in Gatsby?

### ISSUE THREAD

**Issue by oddThomas13** [strapi/gatsby-source-strapi#51]
When I use Markdown in the Strapy text editor, it is displayed in plain text in the front of Gatsby. How to translate it into html?

ex.
Strapi Draft text editor: # My Title 
Gatsby frontend: "# My Title", instead <h1>My Title</h1>

**Comment by qq781548819** [comment]
I have the same doubt,is there anyone help me?

**Comment by humont** [comment]
the Gatsby front end doesn't know to interpret the markdown, so you need to use a markdown interpreter plug in.

[React-Markdown](https://github.com/rexxars/react-markdown) seems to work fine!

Just pull your content into the read-markdown component

`<ReactMarkdown source={data.your-strapi-data} />`

**Comment by lauriejim** [comment]
Thank you for the detail @humont !

**Comment by endymion1818** [comment]
The solution above works, but there's a better one. 

The reason it's not the best solution is that you're parsing Markdown to HTML on the frontend, which incurs a performance cost. Gatsby comes with an API (`onCreateNode`) to do this, and I've successfully implemented it on a project: 

https://github.com/endymion1818/discovermo-fe/blob/master/gatsby-node.js#L101

```
module.exports.onCreateNode = async ({ node, actions, createNodeId, createContentDigest }) => {
  if (node.internal.type === "StrapiPostType") {
      const newNode = {
          id: createNodeId(`StrapiPostType-${node.id}`),
          parent: node.id,
          internal: {
              content: JSON.stringify(
                unified()
                  .use(markdown)
                  .use(html, { sanitize: fieldYouWantToHtmlerize })
                  .processSync(fieldYouWantToHtmlerize)
              ) || " ",
              type: "StrapiPostType",
              mediaType: "text/markdown",
              contentDigest: createContentDigest({
                content: JSON.stringify(fieldYouWantToHtmlerize),
              })
          },
      };
      actions.createNode(newNode);
      actions.createParentChildLink({
          parent: node,
          child: newNode,
      });
  }
};
```
