### ISSUE TITLE
Strapi GraphQL filter sort and where not working

### ISSUE THREAD

**Issue by secretlifeof** [strapi/gatsby-source-strapi#60]
When adding sort or where to query returns error.

**Sort returns:**
Module Error (from ./node_modules/eslint-loader/index.js):
Expected type StrapiModuleSortInput, found "order:asc"

**Where returns:**
If I try where it returns. Unknown argument "where" on field "allStrapiModule" of type "Query".

**My query looks like this:**
```
query LandingPageQuery {
	  allStrapiModule(sort: "order:asc") {
		edges {
			node {
				id
				title
			}
		}
	}
}
```

**Version:**
Gatsby 2.4.2
Gatsby-source-strapi v0.0.8
React 16.8.6

What might be the problem?

**Comment by apollocoder** [comment]
Try it with a object like this:

`query LandingPageQuery {
	  allStrapiModule(sort: _{ fields: [order], order: ASC }_) {
		edges {
			node {
				id
				title
			}
		}
	}
}`

This works for me on 
Strapi v3.0.0-alpha.26.2 
"gatsby-source-strapi": "0.0.8"
"gatsby": "2.8.2"
"react": "16.8.6",

**Comment by navicstein** [comment]
Am still having this issue

**Comment by bryanMeneses** [comment]
This is not working for me either
