### ISSUE TITLE
Error console.timeEnd() when gatsby build

### ISSUE THREAD

**Issue by y0c** [strapi/gatsby-source-strapi#61]
Hi guys, thanks for the plugin.

I have a error when gatsby build.
<img width="590" alt="스크린샷 2019-05-22 오후 6 57 59" src="https://user-images.githubusercontent.com/2585676/58166049-f442db80-7cc3-11e9-8105-2fa2da786e0d.png">

my strapi plugin config
```javascript
 resolve: `gatsby-source-strapi`,
 options: {
 apiURL: process.env.STRAPI_ENDPOINT,
 queryLimit: 1000, // Default to 100
 contentTypes: [`post`, `user`, `archive`],
```
can you help me?

**Comment by davidkartuzinski** [comment]
Hello @y0c - 

Are you following the tutorial?  It's hard to answer you without more details on what you've done or not done.

[Using Strapi and Gatsby Tutorial](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/)

You can look at the repo for the project in the videos. Here is the [config file](https://github.com/strapi/strapi-heroku-cms-demo/blob/master/blog/gatsby-config.js).

-DK

**Comment by luck2011** [comment]
@y0c how did you resolve this error?
