### ISSUE TITLE
Processes images in markdown by Gatsby

### ISSUE THREAD

**Issue by dkarski** [strapi/gatsby-source-strapi#62]
Do you have any idea for processes images in markdown by Gatsby like `gatsby-remark-images`?  Becouse  in this moment any plugins isn't work with `gatsby-transformer-remark`.

[issuecomment-499795525](https://github.com/strapi/gatsby-source-strapi/issues/41#issuecomment-499795525)
[issuecomment-500452716](https://github.com/strapi/gatsby-source-strapi/issues/15#issuecomment-500452716)

**Comment by davidkartuzinski** [comment]
@dkarski - Did you actually try `gatsby-remark-images`?  Did it work?

**Comment by dkarski** [comment]
Yes, I tried. It's not work. Yoy can see in the source code that this plugin not support absolute url
 [https://github.com/gatsbyjs/gatsby/blob/bc8463dd283fb4be17bd7fa38e1ce6d6e15a24f6/packages/gatsby-remark-images/src/index.js#L18](https://github.com/gatsbyjs/gatsby/blob/bc8463dd283fb4be17bd7fa38e1ce6d6e15a24f6/packages/gatsby-remark-images/src/index.js#L18)

**Comment by davidkartuzinski** [comment]
@dkarski - Thank you.  It looks like we need to have the images saved as a relative URL.  This affects the Cloudinary Plugin as well.  

https://github.com/strapi/strapi/issues/3556

**Comment by dkarski** [comment]
Yes, we need like has contenful cms
[https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images-contentful](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images-contentful)

**Comment by davidkartuzinski** [comment]
@dkarski Are you capable of contributing this yourself and perhaps working with @Naismith and @soupette to get it done?  This is a great idea.

**Comment by TheDevDoctor** [comment]
Has any progress been made on this. Currently not being able to use Gatsby images for larger blog posts slows loading times quite a bit. I know that contentful's gatsby plugin works with Gatsby images for rich text images, but I would much rather use Strapi if possible?

**Comment by carstenblt** [comment]
My workaround:

```
// gatsby-node.js
const unified = require('unified');
const remarkParse = require('remark-parse');
const moveImagesToRoot = require('mdast-move-images-to-root');
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)

exports.onCreateNode = async ({ node, actions, getCache, createNodeId }) => {
  const { createNode, createParentChildLink } = actions;
  if (node.internal.type === 'StrapiXXX') {
    const tree = moveImagesToRoot()(unified().use(remarkParse).parse(node.text));

    for (let child of tree.children) {
      if (child.type === 'image') {
        let fileNode = await createRemoteFileNode({
          url: child.url,
          getCache,
          createNode,
          createNodeId,
          parentNodeId: node.id,
        }); // .then() doesn't work?
        createParentChildLink({parent: node, child: fileNode});
      }
    }
  }
}
```

```
export const query = graphql`
  query XXXQuery($name: String!) {
    strapiXXX(name: { eq: $name }) {
      childrenFile {
        url
        childImageSharp {
          gatsbyImageData(
            width: 600,
            quality: 80
            )
        }
      }
    }
  }
`;

<ReactMarkdown
                  children={props.data.strapiXXX.text}
                  components={{
                    img: ({node, ...imgProps}) => {
                      let fileIndex = props.data.strapiXXX.childrenFile.findIndex(file => file.url === imgProps.src);
                     return (<GatsbyImage image={props.data.strapiXXX.childrenFile[fileIndex].childImageSharp.gatsbyImageData} />)
                    }
                  }}
                  />
```

**Comment by alejoar** [comment]
@carstenblt THANK YOU! This should be in the documentation somewhere.

**Comment by JBaczuk** [comment]
Is this not a feature that many people have (displaying inline images in markdown)? I'm curious if I'm just using Strapi incorrectly.
