### ISSUE TITLE
Image in GraphQL doesn't have childImageSharp

### ISSUE THREAD

**Issue by rjain15** [strapi/gatsby-source-strapi#63]
**Describe the bug**
image doesn't have a childImageSharp
```
  36:13  error  Cannot query field "childImageSharp" on type "StrapiArticleImage"  graphql/template-strings
```

**Steps to reproduce the behavior**
1. Go to 'https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/', and follow the steps to add images. 
 
2. Scroll down to the section in the tutorial to update the index.js 
    Adding images
    To add images, we will need to import Img from package gatsby-image installed by default. 
     Replace the content of blog/src/pages/index.js with the following :

     Path: src/pages/index.js

3. Run `gatsby develop`

```
info ℹ ｢wdm｣: Compiling...
 ERROR  Failed to compile with 1 errors                                                                                                     4:13:14 PM
⠀
 error  in ./src/pages/index.js
⠀
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/rjain/code/gatsby-strapi-tutorial/blog/src/pages/index.js
  36:13  error  Cannot query field "childImageSharp" on type "StrapiArticleImage"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 17:54-129
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false
⠀
error ✖ ｢wdm｣:
ERROR in ./src/pages/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/rjain/code/gatsby-strapi-tutorial/blog/src/pages/index.js
  36:13  error  Cannot query field "childImageSharp" on type "StrapiArticleImage"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 17:54-129
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false
info ℹ ｢wdm｣: Failed to compile.

```

**Expected behavior**
I should either see the image in graphql or do I need to use the url, currently the tutorial says, the childImageSharp has the image. 
      image {
          childImageSharp {
            fixed(width: 200, height: 125) {
              ...GatsbyImageSharpFixed
            }
          }
        }

**Screenshots**
In the graphql, I see the image, but there is no childImageSharp?

![image](https://user-images.githubusercontent.com/1404112/58991774-b7d8aa80-87ae-11e9-83e2-6b5f739b5221.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

My index.js is cut-paste from the tutorial. 
Here is the output from strapi http://localhost:1337/articles
```
[{"_id":"5cf7df5ba5092901c002c732","title":"The Karma Spices ","content":"This is the home page of the Karma Spices","createdAt":"2019-06-05T15:27:23.407Z","updatedAt":"2019-06-05T20:45:25.606Z","__v":0,"id":"5cf7df5ba5092901c002c732","user":{"confirmed":true,"blocked":false,"_id":"5cf72f4a0ca16d0289cea696","username":"rjain15","email":"rjain15@gmail.com","provider":"local","role":"5cf72ec90ca16d0289cea5b2","__v":0,"id":"5cf72f4a0ca16d0289cea696"},"image":[{"_id":"5cf829e57502a723166f90f3","name":"Karma.png","sha256":"TItalOoPUlqD9uPK9eCO3qoaD1xUdxQaVAvgWbw6ZpY","hash":"1b22392c85d044b1b5a2fd1c0dbc0863","ext":".png","mime":"image/png","size":"46.91","url":"/uploads/1b22392c85d044b1b5a2fd1c0dbc0863.png","provider":"local","related":["5cf7df5ba5092901c002c732"],"createdAt":"2019-06-05T20:45:25.676Z","updatedAt":"2019-06-05T20:45:25.701Z","__v":0,"id":"5cf829e57502a723166f90f3"}]},{"_id":"5cf7df7aa5092901c002c733","title":"Catalog of Spices","content":"This is the catalog of all the spices","createdAt":"2019-06-05T15:27:54.218Z","updatedAt":"2019-06-05T21:04:28.764Z","__v":0,"id":"5cf7df7aa5092901c002c733","user":{"confirmed":true,"blocked":false,"_id":"5cf72f4a0ca16d0289cea696","username":"rjain15","email":"rjain15@gmail.com","provider":"local","role":"5cf72ec90ca16d0289cea5b2","__v":0,"id":"5cf72f4a0ca16d0289cea696"},"image":[{"_id":"5cf82a9d7502a723166f90f6","name":"large_square_Ceylon__True__Cinnamon__Ground__close.jpg","sha256":"hI-vEXwsNYoXq_5oL5TVIMrjvB4NvmUX1qIa0Us12Mc","hash":"6089ea39075d4ffa9aa41a3d3b446621","ext":".jpg","mime":"image/jpeg","size":"165.12","url":"/uploads/6089ea39075d4ffa9aa41a3d3b446621.jpg","provider":"local","related":["5cf7df7aa5092901c002c733"],"createdAt":"2019-06-05T20:48:29.027Z","updatedAt":"2019-06-05T20:48:29.033Z","__v":0,"id":"5cf82a9d7502a723166f90f6"},{"_id":"5cf82a9d7502a723166f90f5","name":"1200-6356-cardamom-photo3.jpg","sha256":"cNtNveEW1lB0Ef6J2IAKl5L7DMzxTmO7QwN0jIFxbjA","hash":"eeae7454c96547a2ac442988a9577436","ext":".jpg","mime":"image/jpeg","size":"140.81","url":"/uploads/eeae7454c96547a2ac442988a9577436.jpg","provider":"local","related":["5cf7df7aa5092901c002c733"],"createdAt":"2019-06-05T20:48:29.023Z","updatedAt":"2019-06-05T20:48:29.029Z","__v":0,"id":"5cf82a9d7502a723166f90f5"}]},{"_id":"5cf7df8ca5092901c002c734","title":"Catalog of Flours","content":"Catalog of Flours","createdAt":"2019-06-05T15:28:12.803Z","updatedAt":"2019-06-05T21:04:25.038Z","__v":0,"id":"5cf7df8ca5092901c002c734","user":{"confirmed":true,"blocked":false,"_id":"5cf72f4a0ca16d0289cea696","username":"rjain15","email":"rjain15@gmail.com","provider":"local","role":"5cf72ec90ca16d0289cea5b2","__v":0,"id":"5cf72f4a0ca16d0289cea696"},"image":[{"_id":"5cf82b227502a723166f90fc","name":"_DSC5291_Ragi_Flour-500x350.jpg","sha256":"VhYhcNPB4WHsQP5jJZg-n5ZA9xdgchfyxk9cdS1zrZ8","hash":"92aea9504add45909c5b0f7e91517f72","ext":".jpg","mime":"image/jpeg","size":"54.42","url":"/uploads/92aea9504add45909c5b0f7e91517f72.jpg","provider":"local","related":["5cf7df8ca5092901c002c734"],"createdAt":"2019-06-05T20:50:42.762Z","updatedAt":"2019-06-05T20:50:42.773Z","__v":0,"id":"5cf82b227502a723166f90fc"},{"_id":"5cf82b227502a723166f90fa","name":"jowar_rava_2__1__77418.1540025200.jpg","sha256":"-AlSlgyc3NBlhpJDSvxKhVrtqrJKuI7TMQlMViAdp5s","hash":"6566a5be65034e25b102a8ecc9e5715c","ext":".jpg","mime":"image/jpeg","size":"118.22","url":"/uploads/6566a5be65034e25b102a8ecc9e5715c.jpg","provider":"local","related":["5cf7df8ca5092901c002c734"],"createdAt":"2019-06-05T20:50:42.758Z","updatedAt":"2019-06-05T20:50:42.769Z","__v":0,"id":"5cf82b227502a723166f90fa"},{"_id":"5cf82b227502a723166f90f9","name":"Barley-Flour-min.jpg","sha256":"ivT8oDyljKq25haknFroPFqtxnbm1Oz7mxWf65cUQUg","hash":"87eac8544f6c46958fdd84ffcf34f709","ext":".jpg","mime":"image/jpeg","size":"114.85","url":"/uploads/87eac8544f6c46958fdd84ffcf34f709.jpg","provider":"local","related":["5cf7df8ca5092901c002c734"],"createdAt":"2019-06-05T20:50:42.754Z","updatedAt":"2019-06-05T20:50:42.759Z","__v":0,"id":"5cf82b227502a723166f90f9"}]}]
```
**System**
- Node.js version: 
node v10.14.1 
- NPM version: npm v6.9.0
- Strapi version: 
`strapi --version
3.0.0-beta.1`
- Database: mongodb (part of the strapi-docker, and it works perfectly fine) 
- Operating system: MacOS

**Additional context**

**Comment by davidkartuzinski** [comment]
@rjain15 - Did you figure this out?

**Comment by rjain15** [comment]
I did figure this out (not sure why, but I re-did the tutorial 6 watching the video) and I think there might be some issue when i was cut-pasting the code. I am all set till video 6, moving on. Thanks for your help.

**Comment by mensafung** [comment]
error  Cannot query field "childImageSharp" on type "StrapiArticleImage"  graphql/template-strings
I can't solve it, I re-did the tutorial 6 watching the video, but the problem still here

**Comment by davidkartuzinski** [comment]
@mensafung - do you have a repo for your Project?

**Comment by arrudaricardo** [comment]
I could use childImageSharp after disable "Allow multiple files" at media field in strapi.

**Comment by b3u** [comment]
@davidkartuzinski I'm having the same issue, but I'd like to allow multiple files in the media field. Is there a way to use childImageSharp with multiple images?

**Comment by davidkartuzinski** [comment]
> @davidkartuzinski I'm having the same issue, but I'd like to allow multiple files in the media field. Is there a way to use childImageSharp with multiple images?
> Should I open a new issue for this?

@b3u - You could open a new issue and follow the issue template.  The plugin is being addressed but another issue would be correct.

**Comment by nok91** [comment]
it works fine on:

```
const Image = () => {
  const data = useStaticQuery(graphql`
    query {
      placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  `)

  return <Img fluid={data.placeholderImage.childImageSharp.fluid} />
}
```
but on 

 ```
 image {
                    childImageSharp {
                        fixed(width: 200, height: 125) {
                        ...GatsbyImageSharpFixed
                        }
                    }
                }

```

it generate this error:
Module Error (from ./node_modules/eslint-loader/index.js):
`349:21   error    Cannot query field "childImageSharp" on type "StrapiJobvacancyCompanyImage"  graphql/template-strings`

**Comment by davidkartuzinski** [comment]
@nok91 - did you also change this bit, from "fluid" to "fixed", like so:

```
<Img fluid={data.placeholderImage.childImageSharp.fluid}
```
to
``` 
<Img fixed={data.placeholderImage.childImageSharp.fixed}
```

This seems to be the issue unless there are missing images IE. wrong img links.

(And did you restart your Gatsby Dev?)

**Comment by nok91** [comment]
@davidkartuzinski yes I did, the issues persist, I tried to delete node_modules and installed them, downgrade python to version 2.7 again, updated node versione but still getting exact same issue:

works fine on local image using "placeholderImage"  but generate the error on the strapi query:
 `error    Cannot query field "childImageSharp" on type "Strapi`

**Comment by jimmysafe** [comment]
I have the same issue, error Cannot query field "childImageSharp" on type "StrapiProductImages".

anyone with a solution to this?

**Comment by gengengengengen** [comment]
I have the same issue too. "childImageSharp" can be found in local environment but missed in remote production environment.

**Comment by rizwanad** [comment]
Hey @gengengengengen did you find the solution for not working in production environment ?

any help will be appreciated??

**Comment by hchev001** [comment]
Hey @rizwanad @gengengengengen I just happened to stumble upon this issue. I'm having something similar where childImageSharp is found in local environment but is missing in remote production environment. Have any of you found a way to resolve this?

**Comment by adisher** [comment]
`npm install sharp` followed by `gatsby clean` and `gatsby develop` resolved the issue for me. 
Note: If using VSCode, try relaunching it and follow the above steps.

**Comment by LPIX-11** [comment]
Make sure you chose ***Single Media*** while creating the image field.

**Comment by tiagofsanchez** [comment]
> I could use childImageSharp after disable "Allow multiple files" at media field in strapi.

Had the some issue!

**Comment by Sakaluke** [comment]
anyone found a fix ?

**Comment by tiagofsanchez** [comment]
Yes, @Sakaluke - for me, disabling "allow multiple files" on the media field on strapi worked. Good luck.

**Comment by Sakaluke** [comment]
@tiagofsanchez I know that for single types it works, was wondering why it hasnt been fixed for multiple types...

**Comment by tiagofsanchez** [comment]
Oh, I don't know about that @Sakaluke. For me multiple images ins't working.

**Comment by Sakaluke** [comment]
@tiagofsanchez I ended up creating a separate field in Strapi for multiple images and fetching it with useEffect separately without childImageSharp and optimizing images manually instead of letting the plugin do that. Its not the best solution, but it does the job.

**Comment by Ta-Mo** [comment]
> Make sure you chose _**Single Media**_ while creating the image field.

that worked for me!
