### ISSUE TITLE
Images are mixed up using gatsby-image

### ISSUE THREAD

**Issue by vincezun** [strapi/gatsby-source-strapi#64]
I'm following the official tutorial of gatsby-strapi integration here: https://youtu.be/FTzwb49tBvw

The images are mixed up.
![image](https://user-images.githubusercontent.com/49867576/59732509-26246f00-927d-11e9-98de-7ae21f65ea32.png)

The image should be this one:
![image](https://user-images.githubusercontent.com/49867576/59732526-389ea880-927d-11e9-9ca9-949b8badb99a.png)

Relation
![image](https://user-images.githubusercontent.com/49867576/59732783-36891980-927e-11e9-9fd6-9f1ef80c30a2.png)

Query
![image](https://user-images.githubusercontent.com/49867576/59732694-e8741600-927d-11e9-952b-2828a95c7ceb.png)

Node: 10.16.0
Npm: 6.9.0
Strapi: strapi v3.0.0-beta.6
Database: mysql
OS: Windows 10

**Comment by davidkartuzinski** [comment]
@vincezun - I am working on revising and updating the Strapi / Gatsby Tutorial.  Did you feel there was something that could have been more clear?

**Comment by vincezun** [comment]
The

**Comment by vincezun** [comment]
I am able to fetch the data now. The problem now is the images are mixed up.

**Comment by davidkartuzinski** [comment]
> I am able to fetch the data now. My bad.

@vincezun - So, it's okay?

**Comment by vincezun** [comment]
Yes, just the mixed up image is the issue right now.

**Comment by davidkartuzinski** [comment]
@vincezun - do you have your project somewhere?  Can you post the full page's (or template) code including the graphQL query?

**Comment by vincezun** [comment]
https://github.com/vincezun/phd/blob/master/src/pages/tool-hire.js

https://github.com/vincezun/phd/blob/master/src/templates/service-detail.js

**Comment by davidkartuzinski** [comment]
@vincezun - I am sorry I have not yet been able to really take a look more closely.  Are you using the latest version of Gatsby and the Gatsby CLI?  They recently released an upgraded version of their GraphQL GUI -  http:localhost:8000/___graphql - which now has an additional panel that shows all available routes to your data.   Its called explorer, and I think it will help you to debug this issue:

<img width="1680" alt="Screenshot 2019-06-20 at 16 27 40" src="https://user-images.githubusercontent.com/29503118/59857061-6ddbf100-9378-11e9-8a69-d29c3be28591.png">

**Comment by vincezun** [comment]
I'm already using it. Idk, something is wrong.

**Comment by vincezun** [comment]
I observed that not all the images are being fetched when I go to public/static directory. But It fetched some image(account managers) that is being queried. Does this issue belongs to gatsby-source-strapi or the gatsby-source-filesystem?

**Comment by vincezun** [comment]
**What I observed:** 

- When I look to my public/static folder, some images are not being fetched.
- When I go to /__graphql and query for the data that I need using name, the publicURL that appear matched with the name of the image that is in the public/static folder. The thing is the publicURL that was fetched was not the image for that data.
- I go to the database and check if the relationship between the two table are incorrect. What I found was it is actually correct.

The service details also has a relationship with other content type(service overview). 

**This is the relation of content types:**
Service overviews belongs to many Service details. Then, Account managers has and belongs to many Service details. 

This problem will be solved by creating individual content type for each service(parent) but the problem is, I will end up creating individual template and I do not want to do that.

**Comment by davidkartuzinski** [comment]
@vincezun - I have been updating the Gatsby Strapi tutorial and trying to create the same issue as you and cannot. I have asked others to take a look at this and see if we can't resolve this.

**Comment by vincezun** [comment]
@davidkartuzinski can I fetch like this? two context

![image](https://user-images.githubusercontent.com/49867576/59936094-bc28e700-9481-11e9-97e2-dd455079d3de.png)

**Comment by vincezun** [comment]
I already tried that one. Creating individual content type for service.

The relationship now is: 
- Account Managers has many Plant hire.
- Account Managers has many Working platform.

I ended up the same outcome. String and text field is fine but the image field is not. As I said before, it is not getting some image when I look to public/static. There is something wrong there. The weird thing is, plant hire fetched it correctly. Then I have another one  that is actually the same as plant hire, that one is working platforms. And the account managers does not appear. The image that appear is from working platform not from the account manager.

**Comment by vincezun** [comment]
I gave the same image for Craig and Ben. And If you look at the src path and compare it. It is not the same.

![image](https://user-images.githubusercontent.com/49867576/59957445-1306de80-94cb-11e9-8fcb-b9e229b17331.png)

**Comment by vincezun** [comment]
I found a way to make this work but it's not efficient. The image is not included in database and I include a field for the relative path of that image to be fetch. Sorry for the inconvenience. I hope this will be fixed soon.

**Comment by michaelhogersosis** [comment]
I have the same issue where images of different content types are being mixed up. This only occurs when the strapiId is not unique. Say I have a team content type where I use team member images and an article content type with article images. 

If both the team and article content type have the same strapiId (say 3) then the images are being scrambled. This happens occassionally and only seems to be a problem for images.

**Comment by michaelhogersosis** [comment]
@davidkartuzinski if you'd like I am open to demonstrating the issue by sharing my screen with you. Apart from this image mixup issue Strapi works very well with Gatsby. Please let me know, thanks for this wonderful CMS.

**Comment by davidkartuzinski** [comment]
@michaelhogersosis - I would like to see about this. Can you find me in the Slack channel?

**Comment by fabianbuijing** [comment]
I have the exact same issue :) See https://preview.pleio.nl/ at the bottom of the page two illustrations are being swapped with other photographs. They seem to have the same ID number.

**Comment by davidkartuzinski** [comment]
@michaelhogersosis @fabianbuijing - Can you confirm that clearing the Gatsby cache and restarting both Strapi and Gatsby does *not* fix this?  

Can you try this?
https://www.gatsbyjs.org/docs/debugging-cache-issues/ 

Could you also explain, which DB you're using in Production for the images? For example, a Cloudinary or S3 bucket or VPS hosted, etc...?

**Comment by fabianbuijing** [comment]
@davidkartuzinski Yes, tried `gatsby clean` a lot

We use postgres, images are saved to the filesystem

**Comment by davidkartuzinski** [comment]
> I found a way to make this work but it's not efficient. The image is not included in database and I include a field for the relative path of that image to be fetch. Sorry for the inconvenience. I hope this will be fixed soon.

@vincezun - I just saw something in your code.  You're trying to hardcode the static URL.  This would not be the correct way and I suspect the reason you're having issues. From the Gatsby docs here https://www.gatsbyjs.org/packages/gatsby-image/

**Be aware that from a SEO perspective it is advisable not to change the image parameters lightheartedly once the website has been published. Every time you change properties within fluid or fixed (like quality or maxWidth), the absolute path of the image changes. These properties generate the hash we use in our absolute path. This happens even if the image didn’t change its name.**

Code you please take a look at this section in the Docs: https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images and see if either the **FilesSystem** or **Fluid Query** will better suite your needs (and fix this error)?

**Comment by fabianbuijing** [comment]
@davidkartuzinski as a workaround, we renamed all our `image` fields to a more specific `articleImage`, `memberImage`, etc. Now the images don't get mixed up anymore..

**Comment by davidkartuzinski** [comment]
> @davidkartuzinski as a workaround, we renamed all our `image` fields to a more specific `articleImage`, `memberImage`, etc. Now the images don't get mixed up anymore..

@fabianbuijing - Thank you for posting your workaround.  Until this is fixed, this seems workable.

**Comment by wmlutz** [comment]
This unfortunately doesn't work for me. I have an array object in Strapi that is mixing up the images. There is no good way to undo the name blocking.

**Comment by kataloo** [comment]
> @fabianbuijing - Thank you for posting your workaround. Until this is fixed, this seems workable.

This is workable if only adding new items. If you want to change an image in an existing item, the issue still presents.

**Comment by davidkartuzinski** [comment]
> This is workable if only adding new items. If you want to change an image in an existing item, the issue still presents.

@kataloo - Sorry to hear that you are still having issues with this.  Have you tried 

```bash
$ gatsby clear 
```

And then rebuilding Gatsby? 

I haven't following the new tutorial, https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi/ but I know it says to use the ```gatsby-source-strapi``` plugin.

I am actually about to test [Gatsby Source GraphQL](https://www.gatsbyjs.org/packages/gatsby-source-graphql/
) instead of the source plugin and see if that resolves this issue and perhaps others. This was a @Aurelsicoko's recommendation in a recent video. [recent Strapi Recap Video](https://strapi.io/blog/strapi-online-meetup-1-recap
).

Good luck and I am sorry I couldn't be more help.

**Comment by 8byr0** [comment]
Hi there! 
I used to be stuck with the same issue (that's why I reached this thread).

In my case I just upgraded gatsby-cli and now all seems to be working properly, no more images mixed up!

Simply run
```
npm i -g gatsby-cli
gatsby clean
gatsby develop # Or gatsby build
```

I cleaned up / rebuilt multiple times and the issue did not appear any time.

Hope this helps !

**Comment by geertvanleemputten** [comment]
This issue is still happening to me.
v3.0.0-beta.20
array of images => graphql result all mixed up

**Comment by MrRobotjs** [comment]
Same issue here. Pulling Multiple media types from the same category will have the images all mixed up.

**Comment by andreadev-it** [comment]
I had the same issue in my project. I have two different content types (products and events) that have an 'image' field. The event with id 'Events_2' was showing the same image as 'Products_2', even though it wasn't supposed to. 
In my situation, changing the name of one of this fields to 'logo' instead of 'image' actually solved the problem (for now at least).

**Comment by andreadev-it** [comment]
Looks like #102 could solve the problem. I wasn't able to replicate the issue anymore, but if someone still have this problem, it might be useful to try that one out.
