### ISSUE TITLE
Consider handling trailing forwardslash for apiURL

### ISSUE THREAD

**Issue by Skraelingjar** [strapi/gatsby-source-strapi#69]
Hello,

I was a pit perplexed today trying to connect to my remote server. It wasn't until looking at source did I realize that a slash is manually added in [fetch.js](https://github.com/strapi/gatsby-source-strapi/blob/976f21037a8ead3b1454d4904a8616be36ea55bf/src/fetch.js#L10) and updated my config. 

Having looked through the tutorial previously, I don't remember this being documented. Maybe it could be handled or documentation added stating not to add a slash. Happy to submit a PR either way.

**Comment by davidkartuzinski** [comment]
@Skraelingjar Thank you very much for this comment.  To clarify, you are referring to the URL for apiURL?

```
    {
      resolve: 'gatsby-source-strapi',
      options: {
        apiURL: 'http://localhost:1337',
        contentTypes: [ // List of the Content Types you want to be able to request from Gatsby.
          'article',
          'user'
        ],
        queryLimit: 1000,
      },
```

Several people were tripped up with this, and I believe I address it in the video.  I have updated the
[blog post tutorial](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/).

Does this clarify it for you?

*****
**NOTE:** Please understand that the `apiURL:`, e.g. `http://localhost:1337` does **NOT** have a trailing slash.  This will create issues, as a slash is added by other code in the plugin.
*****

Thanks again, and we welcome all thoughts and help like this!

**Comment by Skraelingjar** [comment]
Ahh, I didn't watch the video. Yes, I am referring to the URL for apiURL. 
Thanks for adding it to the blog post. Hopefully, nobody else will make the same mistake I did.
