### ISSUE TITLE
No API updates in Gatsby

### ISSUE THREAD

**Issue by decimoseptimo** [strapi/gatsby-source-strapi#7]
Upon `$ gatsby develop`, strapi seems to load fine, with just a warning `(node:5008) Warning: No such label 'Fetch Strapi data' for console.timeEnd()`.

On the first compile, the Strapi API will be fetch normally.
Then I proceed to perform a content update in the Strapi GUI, save, and fetch via browser to ensure the update took place.
Then I enforce a subsecuent compile in gatsby, which updates content as usual, except for Strapi API content, no errors thrown.

I have to restart `$ gatsby develop` to get new content but again only the first fetch will succeed.

**Comment by olakaldestad** [comment]
Gatsby only fetches content from sources when you first run `gatsby develop`, this is a feature. Subsequent 'recompiles' do what they should; recompile, not fetch data. However, if you still feel like this is an issue and should be resolved somehow, I would suggest taking that up with the good people over at [Gatsby](https://github.com/gatsbyjs/gatsby), as this really isn't a Strapi related matter.
