### ISSUE TITLE
how does gatsby comunicate with strapi via graphql, if strapi has no graphql instaled?

### ISSUE THREAD

**Issue by ionutale** [strapi/gatsby-source-strapi#82]
how does gatsby communicate with strapi via graphql, if strapi has no graphql instaled?

i read the docs and now how it creates the schemas for the graphiql, but when you build and deploy to prod, how does gatsby communicate with strapi if strapi has no schema declared?

i am very confused

**Comment by lauriejim** [comment]
It's because GraphQL requests you do in Gatsby request the Gatsby GraphQL interface.
And then Gatsby fetches the needed data to Strapi via the REST API.

**Comment by ionutale** [comment]
so is just simulating graphql support?

so the plugin, makes a request, analyzes the data, and then create the graphql schema?
is this correct?

**Comment by lauriejim** [comment]
Yap
