### ISSUE TITLE
childImageSharp is not applied to images in groups

### ISSUE THREAD

**Issue by masives** [strapi/gatsby-source-strapi#88]
When image(of type media) is directly under the content type it is assigned type File and it is processed by childImageSharp 

However when it's in group then it's not assigned type of File but rather a string of parent and groupname. 

Is there any solution for using sharp optimization on images nested in groups?

**Comment by lamellama** [comment]
```
GraphQL Error Unknown field `childImageSharp` on type `heroimage_3`

   1 | 
   2 |   query PageById($id: String!) {
   3 |     strapiPage(id: {eq: $id}) {
   4 |       id
   5 |       slug
   6 |       title
   7 |       
   8 |       hero{
   9 |         heroimage {
> 10 |           childImageSharp {
     |           ^
  11 |             fluid(maxWidth: 960) {
  12 |               ...GatsbyImageSharpFluid
  13 |             }
  14 |           }
  15 |         }
  16 |         title
  17 |         subtitle
  18 |       }
  19 |     }
  20 |   }
```

It seems to me the heroimage should be of type file.

**Comment by lamellama** [comment]
It seems there is a PR for this already: https://github.com/strapi/gatsby-source-strapi/pull/83

**Comment by masives** [comment]
I'm closing the issue then
